### ISSUE TITLE
Can’t open .realm db file(created on Android) with encryption key on Mac

### ISSUE THREAD

**Issue by Kolyall** [realm/realm-studio#1003]
**Describe the bug**
Can’t open .realm db file(created on Android) with encryption key on Mac

**To Reproduce**
 classpath "io.realm:realm-gradle-plugin:5.4.2"
Db file: 
https://www.dropbox.com/s/g89o9xgqsigscsi/current_user.realm?dl=1
Trying to open created DB on Android with encryption key 30443764596546573252715a74414a4f424246425871574f324b513d0a567351386e557770567351386e557770567351386e557770567351386e557770567351

**Expected behavior**

**Screenshots**
![ffe392bbdb632826377b51dea0b8d8274bb88450_1_619x499](https://user-images.githubusercontent.com/3495165/48551342-4f93ab80-e8e6-11e8-8145-9bf80a743dd6.png)

**Versions:**
 - OS:  Mac
 - Studio Version 3.0.6

**Additional context**

**Comment by nirinchev** [comment]
Realm encryption is not platform-agnostic - it depends on the platform's page size. So generally, you should not expect to be able to share encrypted realms between different operating systems.

**Comment by nirinchev** [comment]
Looking at the error message, it seems like this is a corrupted Realm file, not a page size error. Are you sure you can open this Realm on Android?

**Comment by Kolyall** [comment]
@nirinchev Yes, It works fine on Android

**Comment by nirinchev** [comment]
It sounds to me like the Realm file was corrupted when copying from the device.

**Comment by Kolyall** [comment]
@nirinchev I used the command:
`adb -d shell "run-as com.example.test cat /data/data/com.example.test/files/data.db" > data.db`

**Comment by Kolyall** [comment]
You are right. Thanks. The pull command on Android Studio sometimes crashes.

**Comment by Kolyall** [comment]
@nirinchev Now, why the file is empty?... but when I open it with TextEdit application it is not empty
https://www.dropbox.com/s/31mge4g0aej82yw/place_profile.realm?dl=1
![2018-11-15 15 56 03](https://user-images.githubusercontent.com/3495165/48554304-1ca1e580-e8ef-11e8-8fb0-65f5793b75b2.png)
