### ISSUE TITLE
User is unable to upgrade on Windows from 3.0.6 to 3.0.7

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-studio#1015]
**Describe the bug**
Reported on Forums: https://forum.realm.io/t/realm-studio-3-0-5-shows-menu-only/2150/6

**Versions:**
 - OS: Windows
 - Studio Version 3.0.6

**Comment by kraenhansen** [comment]
I answered on the forum: https://forum.realm.io/t/realm-studio-3-0-5-shows-menu-only/2150/8?u=kraenhansen - the fix was introduced iwith https://github.com/realm/realm-studio/pull/1004 released as Studio 3.0.7.
