### ISSUE TITLE
@Required not allowed on RealmList's that contain other Realm model classes on models saved from Realm Studio

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#1025]
@southerton81 commented on [Wed Nov 28 2018](https://github.com/realm/realm-java/issues/6356)

#### Goal
@Required field should not be added on target fields by Realm Studio 

#### Actual Results
@Required field is added on target fields by Realm Studio 

#### Steps & Code to Reproduce
File->Save model definitions-> Kotlin in RS would add @Required into source snippets that contain other Realm model classes. This produces compile-time errors.

#### Version of Realm and tooling
Realm Studio 3.0.7

**Comment by kraenhansen** [comment]
As per the conversation on https://github.com/realm/realm-studio/pull/483 perhaps @nhachicha wants to take a look at this?

**Comment by sipersso** [comment]
Looks like this error is not only on realm studio but also in MongoDB atlas. The kotlin models generated via MongoDb Realm also get the @Required annotation and don't compile. Strangely enough it does seem to compile for the support staff, but it does not work for me in Android studio.
