### ISSUE TITLE
Cannot authenticate to a server using admin token

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#1030]
**Describe the bug**
Authenticating with an admin token was broken when we started using serialization / deserialization of users: https://github.com/realm/realm-studio/pull/973 (first released as Studio v3.0.0)

**To Reproduce**
1. Connect to a server using an admin token as authentication method.
2. See how the initial authentication works but once the browser opens the users sees "The path is invalid or current user has no access."

**Expected behavior**
A user would expect to be able to authenticate using an admin token.

**Screenshots**
None.

**Versions:**
 - OS: All
 - Studio Version v3.0.0
 - Realm Object Server version: N/A

**Additional context**
The underlying issue was fixed with Realm JS 2.21.0.

**Comment by kraenhansen** [comment]
I had to revert this change with https://github.com/realm/realm-studio/pull/1034 due to https://github.com/realm/realm-js-private/issues/498.

**Comment by cmelchior** [comment]
Weird, that method just sets some private fields on the SyncManager, it shouldn't start or instantiate anything. Or well, it calls `configure_file_system` in Object Store, but that is done eventually anyway

**Comment by kraenhansen** [comment]
Fixed by https://github.com/realm/realm-studio/pull/1038

**Comment by kraenhansen** [comment]
It seems Realm JS 2.21.0 has a regression when running on Windows, which is holding back a release of this fix. I've talked with @kneth in person, who is currently investigating if downgrading core or sync will fix this.

**Comment by kraenhansen** [comment]
This was fixed again with https://github.com/realm/realm-studio/pull/1050 and release as Realm Studio 3.1.3.
