### ISSUE TITLE
As a user I want to be able to edit a RealmList in Studio

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#1048]
As a user I want to be able to edit a RealmList in Studio, e.g. in the screenshots below I have a list of Items under a Project. If I by accident create the object first in Item, there doesn't appear to be a way to add it to the list afterward. I need to create it directly in the list. 

Also, Realm lists are ordered, so having some way to re-order them would be nice as well.

![image](https://user-images.githubusercontent.com/406066/49930444-e98a4c00-fec4-11e8-8c20-85ab491d88e4.png)
![image](https://user-images.githubusercontent.com/406066/49930510-0de62880-fec5-11e8-9e96-855b9f4288ed.png)

TODO:
- [ ] Be able to add a reference to an existing object that is already created
- [ ] Be able to re-arrange elements in the list.
- [ ] Be able to delete elements from the list.

**Comment by kraenhansen** [comment]
Have you tried drag and dropping to reorder and right-clicking to delete and add rows? :-) If that is not how you would have thought to access these features, how would you?

**Comment by cmelchior** [comment]
Yeah, I can see all of that working and not sure it can be made more intuitive than that either. I'm not 100% sure what kind of problems I ran into that prompted me to create this issue.

Anyway. I'll close it for now and reopen if I remember what the issues were 😄
