### ISSUE TITLE
Realm not defined error on opening realm file on windows realm studio

### ISSUE THREAD

**Issue by ironage** [realm/realm-studio#1086]
@bhavin1701 commented on [Thu Jan 17 2019](https://github.com/realm/realm-js/issues/2224)

---

@bhavin1701 commented on [Thu Jan 17 2019](https://github.com/realm/realm-js/issues/2224#issuecomment-455307860)

![untitled](https://user-images.githubusercontent.com/29137795/51344575-f3c0dc80-1a66-11e9-8d8a-b6380797e91e.png)

---

@bhavin1701 commented on [Thu Jan 17 2019](https://github.com/realm/realm-js/issues/2224#issuecomment-455308047)

working fine on mac OS on realm browser

**Comment by sittingInFront** [comment]
I have the same issue on win7

**Comment by kraenhansen** [comment]
Unfortunately Realm Studio is not supported on Windows 7. We're tracking https://github.com/realm/realm-studio/issues/463 to give users a better error message.
