### ISSUE TITLE
A basic studio feature: refresh button.

### ISSUE THREAD

**Issue by wdcurry** [realm/realm-studio#1096]
A simple feature ALL db management tools have: the ability to tap a refresh icon to ensure the latest contents on a data table listing.  If it is available on my Mac studio, I am missing it.  I am currently cmd-quiting and reopening, which is just wrong ;)

**Comment by wdcurry** [comment]
Well maybe I spoke too soon. I have recently started with Realm and perhaps my methodologies are not efficient as yet, as just now, just after finally posting this, I have seen a new record appear in the object list and am seeing field updates.  I wonder what was keeping it from updated prior to now?

**Comment by bmunkholm** [comment]
We should be showing live updates as they occur in the file and are synced. I'm not sure how you could have experienced anything else than that. But if you do, please get back with details on how to reproduce. Thanks!

**Comment by wdcurry** [comment]
Thanks, and this of course makes sense. At present the only thing I can think of is that my debugging process somehow interrupted things. Running straight UI (old-school) testing is showing instant updates in the studio.
