### ISSUE TITLE
Permission sidebar of the browser maps incorrectly when filtering the table

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#1112]
**Describe the bug**

Similar to https://github.com/realm/realm-studio/issues/1085, selecting an object in a partial Realm from a filtered table shows object level permission for the object at the same position in the unfiltered list of results.

**To Reproduce**
1. Open a partial Realm with the browser.
2. Select an object and note its position in the unfiltered list.
3. Perform a notable permission change to the object.
4. Apply a filter to the table.
5. Observe how the permission sidebar doesn't follow the object but rather the object at the position in the table.

**Expected behavior**
The permission sidebar should show permissions for the selected object, regardless of the table filtering.

**Versions:**
 - OS: All platforms
 - Studio Version 3.3.0
 - Realm Object Server version N/A

**Comment by cedvdb** [comment]
Still happening on 3.6.1
