### ISSUE TITLE
Realm Studio helper consumes 100% cpu on macOS

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-studio#1125]
**Describe the bug**
After Studio has been running for some time (hours) without me touching anything, it suddenly starts consuming 100% cpu for no obvious reason.

**To Reproduce**
1. Start Studio
2. Open a Realm browser, so that now there are 3 studio windows - the browser, the server admin screen, and the connect to server screen.
3. Leave it for some hours
4. Listen for your fans spinning like crazy and notice the Realm Studio Helper process is taking 100% cpu.

**Expected behavior**
Studio should be idling and not consuming any CPU.

**Screenshots**
Windows I had open when I noticed the problem:
<img width="1412" alt="screen shot 2019-03-01 at 20 53 17" src="https://user-images.githubusercontent.com/2315687/53662901-79d66280-3c64-11e9-83e7-b08e7ad4873b.png">

Activity monitor:
<img width="561" alt="screen shot 2019-03-01 at 20 56 56" src="https://user-images.githubusercontent.com/2315687/53662937-95416d80-3c64-11e9-856d-8fb09e67486f.png">

**Versions:**
 - OS: Mac
 - Studio Version: 3.4.0
 - Realm Object Server version: not relevant

**Comment by qexpres** [comment]
I believe that the server admin screen (top right window in screenshot) is the problem. It's the only screen that becomes unresponsive. You can, however, just close the screen and open a new one by reconnecting using the connect to server screen (bottom window in screenshot). I'm not entirely sure, but I think it also solves the CPU problem until it happens again.

**Comment by kraenhansen** [comment]
I would love to know if anyone has a sure way to reproduce this in a way that doesn't involve "Leaving it for some hours".

**Comment by nirinchev** [comment]
This seems to happen if you connect to a server that then gets disconnected - e.g. it happened to me when I was running ROS locally, connected to it, then killed ROS. I only needed the ROS admin screen opened to reproduce the issue and it happens a couple of minutes after ROS is killed.

**Comment by pierre-moire** [comment]
I have exactly the same problem. It occurs almost immediately after opening.

**Comment by kraenhansen** [comment]
@pierre-moire after opening what? Do you connect to the server, does it disconnect from the server, do you use the Realm browser? I still havn't been able to find a reliable way to reproduce this issue.
