### ISSUE TITLE
Other classes duplicates rows when adding new classes

### ISSUE THREAD

**Issue by johnernest02** [realm/realm-studio#1133]
These is the situation

I have a a Realm Database with a `Users` class

```
Users {
   name: string?
}
```

I then have 1 row here with the value `John Doe`

When I add a new class, this `John Doe` row is duplicated 10 times. So now I have 10 `John Doe` rows in `Users`

**Comment by kraenhansen** [comment]
Interesting. Can I have you record a video or gif showing this behaviour?

**Comment by dev-JE02** [comment]
Yes, please bear with me. I will do it as soon as I can

**Comment by bmunkholm** [comment]
Closing due to no response.
