### ISSUE TITLE
Realm studio take a lot of resources

### ISSUE THREAD

**Issue by pavelpoley** [realm/realm-studio#1144]
Realm studio take a lot of resources, especially at the end of the day when it always open, attached image, both CPU and memory, in some cases its take up to 4GB ram memory.

![realm](https://user-images.githubusercontent.com/33838217/56511482-609bb500-6535-11e9-9d0f-d2ddd59fb9ed.png)

Realm 3.5.0
Windows

**Comment by nirinchev** [comment]
There's already a report about Studio consuming 100% CPU in some cases. As for the ram - 60 MB is quite reasonable. When you open a Realm, it will consume ram based on the size of the Realm and it will release it once the Realm is closed. We don't have reason to believe that Studio itself is consuming a lot of RAM in and of itself. If you have a repro case for such behavior, feel free to reopen the issue.

**Comment by pavelpoley** [comment]
I just opened the studio in the morning, the `Realms` is almost empty about 50 objects total, 4.2GB memory
![Capture](https://user-images.githubusercontent.com/33838217/56587902-06f5c200-65eb-11e9-8c88-a5ae33ab26c3.PNG)

**Comment by kraenhansen** [comment]
@pavelpoley what windows of studio was opened at that point in time? Do you remember what you were doing with Studio during this time?

**Comment by pavelpoley** [comment]
Was opened login window and the main window(with tabs Realm/Users/Logs etc), i did nothing in this day just opened in morning to show you, after 6-7 hours this is the result, i didn't enter any realms and even did't do any transaction in thru Android app we develop with(also the existing realms almost empty)
