### ISSUE TITLE
Feedback Requested: New UI for Realm Studio

### ISSUE THREAD

**Issue by cliftonlabrum** [realm/realm-studio#1156]
I opened an issue related to [dark mode support for macOS](https://github.com/realm/realm-studio/issues/1154), and in the process of trying some things out, I decided to put together a refreshed UI for Realm Studio. Obviously there is a lot of work to be done, but I wanted to gather feedback before I invested more time in this.

Please review the screenshots and let me know what you think. :)

![RealmStudio-Light](https://user-images.githubusercontent.com/2513753/59462376-78c2de80-8dd8-11e9-8741-c8d038cb54c0.png)
![RealmStudio-Dark](https://user-images.githubusercontent.com/2513753/59462384-7ceefc00-8dd8-11e9-9b93-f356bea7f5e6.png)

/cc @bmunkholm

**Comment by bmunkholm** [comment]
Hey @cliftonlabrum - Lovely to see you help out! I personally like this, but I also don't have any UI design skills whatsoever :-) As for more feedback, @kraenhansen who is the primary developer on Studio is currently out until after summer, so you may have noticed not too much happening on Studio right now. He does occasionally give feedback though, but that's not to be expected. Also after our MongoDB merger, I can imagine there might be design style changes going forward. But that's something we could take later.
So unless @kraenhansen looks in it may require a bit of patience. I would, however, encourage others to give feedback as well!

**Comment by bmunkholm** [comment]
As we are likely going to redesign the UI to adapt to MongoDB visuals going forward, it's likely not worth the effort at this time to do a temporary redesign.
