### ISSUE TITLE
Automatic Schema Generation lists @Required for Java for RealmLists

### ISSUE THREAD

**Issue by ianpward** [realm/realm-studio#1163]
The automatic schema generation will take a realm and generate Java schema with the `@required` keyword for RealmLists - this throws a compiler error in Android Studio

**Comment by kraenhansen** [comment]
@ianpward I had a chat with @cmelchior and he mentioned that an error with this message is thrown at compile time:

    @Required not allowed on RealmList's that contain other Realm model classes.

This happens if the `@Required` annotation is used on a `RealmList` of (non-primitive) Realm objects.
