### ISSUE TITLE
Realm studio opening encrypted realm file without asking for encryption key.

### ISSUE THREAD

**Issue by nishantt12** [realm/realm-studio#1164]
I am encrypting realm db as follows:

`        
Realm.init(getApplicationContext());
Realm.setDefaultConfiguration(getEncryptedRealmConfig());

 private RealmConfiguration getEncryptedRealmConfig() {
        RealmConfiguration.Builder builder = new RealmConfiguration.Builder();
        byte[] key = getRealmKey();
        if (key != null) {
            builder.encryptionKey(key);
        }
        return builder.name(REALM_DB_NAME).deleteRealmIfMigrationNeeded().build();
    }

private byte[] getRealmKey() {
        String realmKey = PreferenceUtil.getInstance(this).getString(PreferenceUtil.REALM_KEY);
        try {
            if (realmKey != null) {
                return Base64.decode(realmKey, Base64.DEFAULT);
            } else {
                byte[] key = new byte[64];
                new SecureRandom().nextBytes(key);
                PreferenceUtil.getInstance(this).setString(PreferenceUtil.REALM_KEY, Base64.encodeToString(key, Base64.DEFAULT));
                return key;
            }
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }

    }
`
 File exportRealmFile = new File(context.getExternalCacheDir(), "export.realm");

I use  realm.writeCopyTo(exportRealmFile); to get the copy of the realm. 

But when I open this file in realm browser I don't get the prompt to enter encryption key instead realm studio opens the file and show the data.

**Comment by nirinchev** [comment]
writeCopyTo writes an unencrypted copy of the Realm which is why you're not getting prompted for a key. It would be a major security flaw if a piece of software could magically read the data of encrypted Realms.
