### ISSUE TITLE
Users are not prompted to download compatibility versions for ROS < v3.20.1

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#1207]
**Describe the bug**

After upgrading Realm JS to the latest version we've introduced a breaking in that Studio can no longer connect to old ROS servers (connecting to ROS v3.18.5 is confirmed to be broken). @kspangsege did a calculation suggesting that the last ROS supported by the current version of Realm Studio is v3.20.1.

We should release a compatibility version of Realm Studio (which will not auto-update to the latest release) branching off from v3.7.0 (the last release before the Realm JS upgrade) and add this to the [list of compatibility versions](https://github.com/realm/realm-studio/blob/master/src/ui/ServerAdministration/index.tsx#L104-L105) that Studio will prompt the user to download.

**To Reproduce**
1. Connect to a ROS server older than v3.20.1.
2. See various failures, possibly resulting in a blank users table.

**Expected behavior**
A prompt to download the compatibility version.

**Versions:**
 - OS: Any
 - Studio Version v3.8.0
 - Realm Object Server version < v3.20.1

**Comment by nirinchev** [comment]
Do we have customers that are running such an old version of ROS? I wouldn't invest effort in that unless we have a report that someone is facing issues.
