### ISSUE TITLE
Studio should not use Recover for client resync mode

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-studio#1230]
**Describe the bug**
Studio attempts to recover local changes when a client reset occurs. Instead it should enforce `clientResyncMode: Realm.Sync.ClientResyncMode.Manual`.

**To Reproduce**
1. Create a Realm
2. Define its schema
3. Delete the Realm
4. Create the Realm again
5. Open the Realm and observe that the old schema is preserved because Studio handles the client reset transparently and recovers its pre-reset changes.

**Expected behavior**
Studio should not modify the server Realm

**Versions:**
 - OS: Mac
 - Studio Version: 3.8.3
 - Realm Object Server version: Cloud

**Additional context**

**Comment by kraenhansen** [comment]
Is there any reason the resync mode should not be "discard" instead of "manual"?
