### ISSUE TITLE
How to use time type to query

### ISSUE THREAD

**Issue by BigSteel** [realm/realm-studio#1237]
Don't know how to use time filtering in realm studio

**Comment by BigSteel** [comment]
![image](https://user-images.githubusercontent.com/5989219/71157122-54aaf300-227c-11ea-8845-4026f15d1316.png)

**Comment by kraenhansen** [comment]
Hi there. I'm sorry this is not that obvious, but Realm Studio uses the Realm JS / Core query parser - documentation for this is available on https://realm.io/docs/javascript/latest/api/tutorial-query-language.html.

In particular, here is the section on timestamps:

> Normally queries can be written with variable substitution so that the syntax of dates is taken care of by Realm. However, sometimes it fits better to compose a entirely string based query. In that case the syntax follows the formats `YYYY-MM-DD@HH:MM:SS:N` or `YYYY-MM-DDTHH:MM:SS:N` where the `:N` suffix specifies nanoseconds but can be omitted (defaulting to 0). If preferred, a programmatic format is also supporting `TSS:NS` which is a literal `T` followed by seconds since epoch, and nanoseconds modifier. In both formats, negative nanoseconds are considered invalid syntax. Timestamps are not quoted like strings. Due to platform limitations, using the first syntax is not supported for dates pre epoch on windows and pre 1901 on other platforms.
> ```javascript
> realm.objects('Person').filtered('birthday == 2017-12-04@0:0:0') // readable date omitting nanoseconds (assumes 0)
> realm.objects('Person').filtered('birthday == 2015-7-2@14:23:17:233') // readable date including nanoseconds
> realm.objects('Person').filtered('birthday == T1435846997:233') // equivalent to above
> realm.objects('Person').filtered('birthday == 1970-1-1@0:0:0:0') // epoch is the default non-null Timestamp value
> ```

I'll close this for now, please reopen if you find any issues following the documentation above ☝️
