### ISSUE TITLE
Unable to open a realm at path '/Users/../default.realm': Invalid top array (ref: 1488, size: 11)

### ISSUE THREAD

**Issue by tvtoan** [realm/realm-studio#1241]
**Describe the bug**
When open default.realm exported from react-native project. React-studio show error.

**To Reproduce**
1. Use realm in react-native project
2. Run react-native project
3. Android: Use Android Studio to export default.realm file at path: /data/data/\<package\-name\>/files/default.realm. iOS: get file by path: /Users/\<username\>/Library/Developer/CoreSimulator/Devices/\<simulator\-uuid\>/data/Containers/Data/Application/\<application\-uuid\>/Documents/
4. Open default.realm
5. React-studio show error

**Expected behavior**
Open and interaction with default.realm file

**Screenshots**
![Screen Shot 2019-12-24 at 10 49 16 AM](https://user-images.githubusercontent.com/9206452/71408770-e9916000-2671-11ea-8b3e-7afcbd943129.png)

**Versions:**
 - OS: Mac - 10.14.5
 - Studio Version - 3.8.3
 - realm-js - v4.0.0-beta.0

**Comment by kraenhansen** [comment]
This type of error is typical of a corrupted Realm file, but I can see that you're opening a v4 Realm JS file with the latest version of Studio (which uses Realm JS v3 internally). We have a beta version of Studio with the beta version Realm JS v4 available for download here: http://studio-releases.realm.io/v3.9.0-beta.0

1. Would it be possible for you to upload the file here?
2. Would it be possible for you to share the app that produced the file? Or even better paste the least amount of code needed to produce a Realm that renders this behavior?
3. If you need to get going, you can try downloading the beta version of Realm Studio and try opening the file with that.

**Comment by softmastx** [comment]
<img width="688" alt="Screen Shot 2562-12-28 at 06 23 09" src="https://user-images.githubusercontent.com/1833053/71535729-9dc50c00-293a-11ea-9894-65d03d30906d.png">
I spent a whole day trying to get it work with react native 0.61.5 !!!

Mine got 

> Unsupported Realm File Format

 when trying to open an existing realm file in react native.

After upgraded to Realm Studio 3.9.0-beta.0, it seems to work now!

Thanks a lot.

**Comment by aashirMIQ** [comment]
@tvtoan have you got resolved this error?

**Comment by tvtoan** [comment]
@aashirMIQ The same @softmastx I upgraded to Realm Studio, it seems to work. 
If your use Realm DB 3.6.0 should use Realm studio 3.8.3 and Realm DB > 3.6.0, you should Realm studio 3.9.0.

**Comment by kraenhansen** [comment]
@tvtoan thanks for reporting back - I'll close the issue.

**Comment by i-schuetz** [comment]
Where to find the matching Realm Studio version for a given Realm version?

**Comment by kraenhansen** [comment]
I believe I've answered you [on our forum](https://community.mongodb.com/t/compatibility-table-realm-studio-realm-library/2101/1), but I'll just be cross-posting here for anyone else that might be interested in the answer:

> Historically Realm Studio has always had compatibility with all versions of the Realm file format released after its inception. So - there hasn’t been a real need for a table like this. This is not the case with Realm core 6 (which is used by Realm Java 7). There’s no official release of Realm Studio, which is compatible with Realm core 6 - but we’ve made a beta release https://github.com/realm/realm-studio/releases/tag/v3.9.0-beta.0 which you can use until an official release is out.

**Comment by hamedaakhlaghi** [comment]
I had this problem on
 mac 10.15.3
 Realm Studio 3.10.0
file
