### ISSUE TITLE
Issue opening a Realm

### ISSUE THREAD

**Issue by RatatatRichie** [realm/realm-studio#1245]
**Describe the bug**
On trying to open a cloud-based Realm on the ROS window..
Clicking the 'Open' button not working. The button stays pressed but nothing happens. I cannot open the realm.

**To Reproduce**
3. See error

**Expected behavior**
I expect to open the realm in realm studio.
Screen shots show before and after clicking 'Open' button
<img width="263" alt="Screenshot 2020-01-07 at 17 03 18" src="https://user-images.githubusercontent.com/3409332/71913644-d0a7a500-316f-11ea-9423-9907a5c7dab5.png">
<img width="267" alt="Screenshot 2020-01-07 at 17 02 32" src="https://user-images.githubusercontent.com/3409332/71913649-d43b2c00-316f-11ea-9c51-c07c69fbe225.png">

**Screenshots**

**Versions:**
 - OS: Mac Catalina 
 - Studio Version 3.8.3
 - Realm Object Server version  3.28.0

**Additional context**

**Comment by kraenhansen** [comment]
Thanks for creating an issue. It might be confusing choice of colors but the open button seems active / focused to me, not pressed. Please share the Relam Cloud server URL with me via email info@realm.io with a link to this comment.

Thanks.

**Comment by kraenhansen** [comment]
Also - what happens if you double-click the Realm in the table of Realms?

**Comment by RatatatRichie** [comment]
*what happens if you double-click the Realm in the table of Realms?*

The right-hand pane opens with the non-functional Open button as before.

Interestingly, the default  realm in the table of realms does open.

Rich

**Comment by RatatatRichie** [comment]
Hi Kraen

Sorry, found the problem. Embarrassingly simple:
The RealmStudio window for the offending realm had been minimized (on iMac)
The open button doesn't maximize it.
It's all working now.
Thanks for the trouble
Do I need to do anything with the issue?

Rich

**Comment by kraenhansen** [comment]
Thanks for getting to the bottom of it. I've change the title to reflect the root cause. It's an issue that I believe we should get fixed, so let's keep it open.

**Comment by kraenhansen** [comment]
I've created https://github.com/realm/realm-studio/issues/1247 to solve the root cause of the confusion. Thanks for reporting this!
