### ISSUE TITLE
Save credentials for Realm Cloud

### ISSUE THREAD

**Issue by raudabaugh** [realm/realm-studio#1253]
**Is your feature request related to a problem? Please describe.**
Realm Studio will occasionally log me out of Realm Cloud on its own, requiring me to dig up my password.

**Describe the solution you'd like**
Never log me out of Realm Cloud unless I manually do so.

**Describe alternatives you've considered**
On macOS, use Keychain to autofill saved password.

**Comment by kraenhansen** [comment]
Although annoying, this is a security feature. The that token that we retrieve from the Realm Cloud backend is only valid for 30 days, after which you need to authenticate - many services do this now-a-days.

If possible, you could authenticate to Realm Cloud using your GitHub account, that way you don't need to find a password when the token expires.

I'll keep this issue open as suggestion on using the Keychain to autofill saved password.
