### ISSUE TITLE
No Error if primary key value is not provided

### ISSUE THREAD

**Issue by hennasingh** [realm/realm-studio#1255]
**Describe the bug**
I created a class with 2 required objects via the Realm Studio. It does not give me an error if I don't provide primary key value

**To Reproduce**
1. Connect to instance via Realm Studio
2. Create a global realm and define a class with 2 or more objects (one primary key) 
3. Provide values to properties, don't give any value to the primary key and it will still create it

**Expected behavior**
Give an error if the value to the primary key was not provided.

**Screenshots**
![image](https://user-images.githubusercontent.com/22836317/72742367-78c26280-3ba1-11ea-9e04-12847e46052f.png)

**Versions:**
 - OS: [Mac]
 - Studio Version [3.9.0]
 - Realm Object Server version [3.28.2]

**Additional context**

**Comment by cmelchior** [comment]
@hennasingh How does the pop-up look? E.g I have this `required` label on fields where values must be provided:

![image](https://user-images.githubusercontent.com/406066/72742933-fb9beb00-3baa-11ea-9693-481e24fb5c26.png)

**Comment by hennasingh** [comment]
thanks @cmelchior , I am assuming @Required is implied if its primary key, please correct me if otherwise. Although I do see the required label there 
![image](https://user-images.githubusercontent.com/22836317/72745893-b24a9c00-3ba8-11ea-9563-ca0b59f55bc2.png)

**Comment by kraenhansen** [comment]
A required property will give an error if the user creates an object with a `null` as the value of said property: Technically the empty string is a perfectly valid string value, hence you don't get an error.
Note that you cannot create two object with the same empty string as primary key.

Try adding an optional string property to the schema and observe the UI when creating an object: The field for the property will start having the special `null` value, until you type something into the field and it can be "cleared" back to its initial `null` value.

We have a known issue in the UI: It's impossible to set back a string to a null value in the table of values: https://github.com/realm/realm-studio/issues/1159.

I believe the behaviour is as expected, although I get that it's fairly confusing that an empty string is considered a valid value for a required string property.

**Comment by hennasingh** [comment]
Thanks @kraenhansen , I did get the error if I try creating another value with empty string but yes, this is confusing. I hope this is meant to resolve in further versions.
