### ISSUE TITLE
Failed to export data: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by solaristhesun** [realm/realm-studio#1257]
I am using version 3.9.0. When I try so save data as JSON I will get the error "Failed to export data: Maximum call stack size exceeded" and no data is exported.

**Comment by kraenhansen** [comment]
Thanks for reporting this! Sorry for the long wait.
We're currently working on improving the exporting of data to JSON from Realm Studio.

**Comment by kraenhansen** [comment]
Would it be possible for you to share the Realm file that you were experiencing this issue with? Is it large or does it contain recursive references?
