### ISSUE TITLE
I can't open default.realm 

### ISSUE THREAD

**Issue by hamedaakhlaghi** [realm/realm-studio#1277]
**Describe the bug**
Today I updated my realm studio, but I can not open `default.realm` with that. I downgraded my realm studio to 3.8.0 but problem is remind

**Expected behavior**
I want to open my realm file

**Versions:**
 - OS: Mac OS
 - Studio Version 3.8.0 and 3.10.0
 

**Additional context**
last week I had not any problem with realm studio

**Comment by kraenhansen** [comment]
Hi Hamed,
Thanks for reporting this.
Is is possible for you to share this file with us?
What errors (if any) do you experience?

**Comment by hamedaakhlaghi** [comment]
The file is correct, I have this problem with the Demo file too. when I try to open it Realm studio does not any action
![Screen Shot 2020-05-05 at 12 18 49](https://user-images.githubusercontent.com/16461249/81045013-973b3800-8eca-11ea-9e28-2ce437907e19.png)

**Comment by hamedaakhlaghi** [comment]
Thanks, My problem resolved, it was mac os bug.

**Comment by kraenhansen** [comment]
Oh okay. I'm glad you found a solution and thanks for reporting back.
I wonder what could have triggered that? 🤔

**Comment by hamedaakhlaghi** [comment]
I can not regenerate it. my realm studio has not any problem but, it was like an invisible line in the left top corner of my mac screen!!

**Comment by kraenhansen** [comment]
Most likely the same issue as https://github.com/realm/realm-studio/issues/1293
