### ISSUE TITLE
Fix upload of GitHub artifacts

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#1285]
For some reason, [the artifacts uploaded on GitHub for v3.11.0](https://github.com/realm/realm-studio/releases/tag/v3.11.0) are abnormally large and corrupted.
The equivalent artifacts uploaded to S3 are fine, which is why I suspect [./scripts/github-releases.js](https://github.com/realm/realm-studio/blob/master/scripts/github-releases.js) might have a bug after the recent upgrade of `@octokit/rest`.

Before fixing this, we should re-upload the artifacts from S3 to GitHub.

**Comment by strawb3rryx7** [comment]
Is there any updates about it? All of the files are corrupted which supplied for macOS. If there is a workaround, or a kind of different URL to reach the files. I'll appreciate.

**Comment by kraenhansen** [comment]
Fixed by https://github.com/realm/realm-studio/commit/3b43cce063c86aa361a0ef99400209f22329afd7 and uploaded the artifacts from S3 onto the GitHub release.
