### ISSUE TITLE
Cannot open realm file in Realm Studio

### ISSUE THREAD

**Issue by natemann** [realm/realm-studio#1293]
## Goals
Open default.realm in realm studio

## Expected Results
Open the default.realm file in realm studio

## Actual Results
Nothing. Nothing happens. I am able to open the default.realm file on other computers. I have deleted / reinstalled Realm Studio multiple times. I am running latest version of Mac OS X. I have given Realm studio full disk access in Settings -> Security. 

I have tried with older versions of Realm Studio (2.9) and still did not work.

Are there hidden files I should delete to get this working? 
Realm framework version: 4.4.1

Xcode version: 11.3

iOS/OSX version: 10.15.4

Realm Studio Version: 3.11

**Comment by bmunkholm** [comment]
The default.realm you are trying to open by which SDK was that created? Was that realm-cocoa 4.4.1? For that version it's best to use Studio 3.10.

As Studio 3.11 supports the newest file-format (10) that is used by realm-cocoa 5.0.0. It should be able to open all realm files, including older ones, but will upgrade them if needed (and they can't be downgraded).

**Comment by natemann** [comment]
@bmunkholm, I have had this issue for quite some time (ever since OS X 10.15 was released). I am currently using realm-cocoa 4.4.1. 

I did open the file on another computer, it did the upgrade, and I was able to view the data.

**Comment by kraenhansen** [comment]
@natemann did that resolve your issue or is this still a problem?
The other computer, was that also a Mac?
Do I understand you correctly, in that you get shown the file picker dialog, but when you select the file and click open, the dialog disappear but the browser never opens?

**Comment by natemann** [comment]
@kraenhansen. My problem is not resolved. I can open it on another Mac running 10.15, but not my primary machine. 

using the dialog box, I pick the file, the dialog box closes, then nothing happens. Also, nothing happens if I double click the file, or right-click the file and select Realm Studio to open. Before Realm 5.0, I was able to open the files using the old Realm File browser. With 5.0, I am not able to open files with Realm file browser any more.

**Comment by puraxays** [comment]
I have the same problem as well. It started after I upgraded to Realm 5.0.1 and Realm Studio 3.11.0. Realm Studio cannot open any realm file. Nothing happens.

**Comment by kraenhansen** [comment]
@natemann & @puraxays would it be possible for you to share the files you're trying to open? Either here or via email (kraen.hansen(at)mongodb.com).

**Comment by puraxays** [comment]
I couldn't open the demo file as well that I've downloaded from Realm Studio. I click "Open Realm file" then choose the "demo.realm", but nothing happens. Screen keeps staying. Please let me know if you need any further info.

By the way Realm works in my project. I just can't browse it.

<img width="701" alt="Screen Shot 2020-06-02 at 11 54 53" src="https://user-images.githubusercontent.com/32415606/83500917-115ddd00-a4c8-11ea-9da9-ffd81adbafa4.png">

**Comment by puraxays** [comment]
Aah, today I found the Realm Studio is already active in an another desktop in a line format. I found by chance. Actually I don't get it because I restarted my machine several times. Anyway, I'm sorry to bother you. It seems it's my fault :)

**Comment by natemann** [comment]
@kraenhansen just sent an email

**Comment by kraenhansen** [comment]
@natemann I've received your email. Thanks. Unfortunately I haven't come around to check the file just yet. You wrote that you can open the file on another computer: Am I right in assuming this is not urgent for you?

**Comment by natemann** [comment]
@kraenhansen it is kind of urgent. the other computer is remotely connecting to a Mac mini. Not very efficient.

**Comment by igrechuhin** [comment]
@natemann I had same problem. In my case the problem was in Realm Studio window. I found it collapsed to zero-width column.

**Comment by natemann** [comment]
@igrechuhin how did you fix this? How did you find the window?

**Comment by natemann** [comment]
The issue is fixed. @igrechuhin was correct.

**Comment by kraenhansen** [comment]
Great news! I've created https://github.com/realm/realm-studio/issues/1313 to ensure the windows are never resized below a certain size.

**Comment by marcuskim1989** [comment]
![Screen Shot 2020-09-14 at 11 44 29 AM](https://user-images.githubusercontent.com/38197966/93125306-ca16e900-f67f-11ea-90a6-8e64dbf344e1.png)

I'm not able to see my data from the main window. Do I have to enter query?

**Comment by cmdr-surender-singh** [comment]
I'm facing the same issue realm cocoa version 5.4.2 
when  I open the realm file on studio it gives me an alert with **Opening Realm files of format version 11 is not supported by this version of Realm**
attached screenshot
![Screenshot 2020-09-21 at 4 10 56 PM](https://user-images.githubusercontent.com/42886349/93758055-606d8080-fc25-11ea-9396-1e244b54048f.png)

**Comment by steffenagger** [comment]
@cmdr-surender-singh that's a different issue, please follow https://github.com/realm/realm-studio/issues/1325 for updates.
