### ISSUE TITLE
Realm Studio 3.10.0 update check doesn't work

### ISSUE THREAD

**Issue by sipersso** [realm/realm-studio#1316]
Not sure if this is fixed in 3.11, but when I open realm studio 3.10.0, it checks for an update, but the app says it is the latest version. Check for updates doesn't work either.

**Comment by kraenhansen** [comment]
Thanks for reporting this.
Because of confusion arising from the upgrade of the Realm file format introduced in v3.11.0, we decided to disable automatically upgrading users from v3.10 until we've solved https://github.com/realm/realm-studio/issues/1303.
