### ISSUE TITLE
Realm Studio 3.11.0 will not open on Mac

### ISSUE THREAD

**Issue by fvlasie** [realm/realm-studio#1317]
<img width="422" alt="Screenshot 2020-07-19 at 12 30 53 am" src="https://user-images.githubusercontent.com/33334298/87869811-880b4880-c957-11ea-9cf7-0c51fdcb4c4b.png">
<img width="583" alt="Screenshot 2020-07-19 at 12 33 20 am" src="https://user-images.githubusercontent.com/33334298/87869815-90638380-c957-11ea-97e4-d615790c785d.png">

**Comment by fvlasie** [comment]
Incidentally the ctrl-click > Open does not work and there is no Open Anyway button in System Preferences.

Thank you!

**Comment by kraenhansen** [comment]
Thanks for reporting this. Unfortunately [Realm Studio is not submitted for notarization](https://github.com/realm/realm-studio/issues/1139). To make it harder to potentially insecure apps, the ability to "open anyway" has moved all the way to the "Security & Privacy" settings screen, for non-notarized apps.

Please try opening Realm Studio and visit the "Security & Privacy" screen on your system preferences to allow Realm Studio to open. If thats not possible, feel free to reopen this issue.

**Comment by fvlasie** [comment]
Thank you for the reply. Unfortunately no "open anyway' button shows up in Security and Privacy:
<img width="653" alt="Screenshot 2020-07-21 at 1 07 51 am" src="https://user-images.githubusercontent.com/33334298/88029251-9b045100-caee-11ea-98c6-7eae236c34e4.png">

**Comment by steffenagger** [comment]
@fvlasie the standard Apple way can be quite buggy. Another way is to run `xattr -rd com.apple.quarantine /Applications/MongoDB\ Realm\ Studio.app` in your terminal.
The above command removes the `com.apple.quarantine` attribute from Studio, and thus Gatekeeper (MacOS security) won't complain (as it will no longer check the file).

**Comment by fvlasie** [comment]
Thanks @steffenagger but I still get the same message 'The Application "Realm Studio" can't be opened'.
It is the same for Realm Studio and MongoDB Realm Studio. I tried it with the latest 10.0.0-beta-2.

**Comment by steffenagger** [comment]
Oh... could you just do a `ls -la /Applications/MongoDB\ Realm\ Studio.app/Contents/MacOS/` and see if `MongoDB Realm Studio` has execution permissions?
If not could you try allowing it with `chmod +x /Applications/MongoDB\ Realm\ Studio.app/Contents/MacOS/MongoDB\ Realm\ Studio`

How did you install them? (dmg/zip etc.)

**Comment by fvlasie** [comment]
Thanks again @steffenagger you seem to have identified the problem!
<img width="421" alt="Screenshot 2020-08-02 at 12 41 20 pm" src="https://user-images.githubusercontent.com/33334298/89130861-7aa89f00-d4bd-11ea-8f53-a2f6c855c35e.png">
It seems to be a problem with the install. I used the zip file.

After downloading the dmg; now it opens but it is asking for my email address!

<img width="698" alt="Screenshot 2020-08-02 at 12 44 45 pm" src="https://user-images.githubusercontent.com/33334298/89131222-fb689a80-d4bf-11ea-8a7d-e502da7963ab.png">
