### ISSUE TITLE
Live update Apple TV Simulator

### ISSUE THREAD

**Issue by adrienyvon699** [realm/realm-studio#1318]
**Is your feature request related to a problem? Please describe.**
Realm Studio live updates are not working when running on an Apple TV simulator

**Describe the solution you'd like**
Have Realm Studio update in real time when running on Apple TV

**Describe alternatives you've considered**
I have to re-open the realm file each time to see the changes

**Additional context**
N/A

**Comment by kraenhansen** [comment]
We don't officially support the Apple TV as a developer platform, hence I haven't personally tried running Realm Studio there.
I'm a bit curious: What is your use-case for running Realm Studio on the Apple TV?
