### ISSUE TITLE
Can not connect to Realm Cloud. 

### ISSUE THREAD

**Issue by kolakovskijj** [realm/realm-studio#1328]
The realm studio can not connect to the server. 

<img width="998" alt="Screen Shot 2020-09-14 at 1 19 37 PM" src="https://user-images.githubusercontent.com/45243948/93141559-065f3f00-f6aa-11ea-852d-2846377ababa.png">

The yellow circle indicates a pending connection, but the connection is never finishing. 

Most recent logs:
<img width="1303" alt="Screen Shot 2020-09-14 at 4 49 02 PM" src="https://user-images.githubusercontent.com/45243948/93141673-39093780-f6aa-11ea-8a9e-d259550c87b7.png">

Tried to create a new instance, but the instance setup never finishes too. 

<img width="1243" alt="Screen Shot 2020-09-14 at 4 49 42 PM" src="https://user-images.githubusercontent.com/45243948/93141731-576f3300-f6aa-11ea-9053-234e01ed4494.png">

Tried to create a new account, and faced the same issue.

**Comment by ianpward** [comment]
@kolakovskijj  Can you open a ticket with support please?

**Comment by bmunkholm** [comment]
Can we close this issue here @kolakovskijj?

**Comment by kolakovskijj** [comment]
@bmunkholm, yes, the support was very helpful. The issue can be closed as of now.
