### ISSUE TITLE
"File > Save Data > JSON" produces empty file

### ISSUE THREAD

**Issue by ryanmeasel** [realm/realm-studio#1344]
**Describe the bug**

I would like to dump my realm database to a JSON file. When using "File > Save Data > JSON," the resulting JSON shows the schema structure but contains no data. 

**To Reproduce**

File > Save Data > JSON

**Expected behavior**

I would have a JSON file populated with the objects from the database.

**Screenshots**

![image](https://user-images.githubusercontent.com/186849/96550814-591ab080-127f-11eb-919f-40cdfb4f4e54.png)

**Versions:**
 - OS: macOS 10.15.7
 - Studio Version: 5.0.0.736
 - Realm Object Server version: not sure how to find

**Comment by steffenagger** [comment]
Hi @ryanmeasel, this looks to be an oversight - Thanks for reporting!

**Comment by kraenhansen** [comment]
This has been fixed and released as Realm Studio 5.0.1, please allow an auto-update or download the new release via https://github.com/realm/realm-studio/releases/tag/v5.0.1

Closing this for now, please reopen if the issue persists after updating.
