### ISSUE TITLE
History type was not consistent across the session crash

### ISSUE THREAD

**Issue by visdyn** [realm/realm-studio#1362]
**Describe the bug**
When opening a local Realm (Sync'd) using MongoDB Studio 10.0.1 it crashes with the following error

History type (as specified by the Replication implementation passed to the DB constructor) was not consistent across the session

**To Reproduce**
1. Start MongoDB Studio 10.0.1
2. Click on Open Realm File, and select a Realm file then click open
3. See error

**Expected behavior**
I would expect the realm file to open without crashing

**Screenshots**
<img width="1491" alt="Realm Studio Crash" src="https://user-images.githubusercontent.com/19558530/99152366-5ab57980-266f-11eb-985f-bb3b2b33af66.png">

**Versions:**
 - OS: macOS 10.15.7 and an macOS App
 - XCode: 12.2
 - Studio Version 10.0.1

**Additional context**
This is a brand new project with very little code. There are three objects in the Realm which are syncing correctly to MongoDBAtlas and are visible and correct int he console

** Realm Model **
```
class UserClass: Object {
    @objc dynamic var _id: ObjectId = ObjectId.generate()
    @objc dynamic var _partitionKey = Constants.USERS_PARTITION_VALUE //resolves to a String of "Users"
    @objc dynamic var user_name = ""
    @objc dynamic var user_id = ""

    convenience init(withName: String, andId: String) {
        self.init()
        self.user_name = withName
        self.user_id = andId
    }

    override static func primaryKey() -> String? {
        return "_id"
    }
}
```

**Textual Backtrace**
Exception backtrace:
0 .com.mongodb.realm-studio.xU50Kf 0x000000010f21d8f7 _ZN5realm2DB7do_openERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEbbNS_9DBOptionsE + 6631
1 .com.mongodb.realm-studio.xU50Kf 0x000000010f21fd73 _ZN5realm2DB4openERNS_11ReplicationENS_9DBOptionsE + 243
2 .com.mongodb.realm-studio.xU50Kf 0x000000010f224986 _ZN5realm2DB6createERNS_11ReplicationENS_9DBOptionsE + 342
3 .com.mongodb.realm-studio.xU50Kf 0x000000010eccadb5 _ZN5realm5_impl16RealmCoordinator7open_dbEv + 1277
4 .com.mongodb.realm-studio.xU50Kf 0x000000010ecc9d42 _ZN5realm5_impl16RealmCoordinator12do_get_realmENS_5Realm6ConfigERNSt3__110shared_ptrIS2_EENS_4util8OptionalINS_9VersionIDEEERNS8_17CheckedUniqueLockE + 62
5 .com.mongodb.realm-studio.xU50Kf 0x000000010ecc9ba8 _ZN5realm5_impl16RealmCoordinator9get_realmENS_5Realm6ConfigENS_4util8OptionalINS_9VersionIDEEE + 530
6 .com.mongodb.realm-studio.xU50Kf 0x000000010ecb3f8e _ZN5realm5Realm16get_shared_realmENS0_6ConfigE + 128
7 .com.mongodb.realm-studio.xU50Kf 0x000000010eb9e1ca _ZN5realm2js10RealmClassINS_4node5TypesEE19create_shared_realmEN4Napi3EnvENS_5Realm6ConfigEbONSt3__13mapINS9_12basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEENSA_ISG_NS0_9ProtectedINS5_5ValueEEENS9_4lessISG_EENSE_INS9_4pairIKSG_SJ_EEEEEESL_NSE_INSM_ISN_SQ_EEEEEEONSA_ISG_NSH_INS5_8FunctionEEESL_NSE_INSM_ISN_SW_EEEEEE + 234
8 .com.mongodb.realm-studio.xU50Kf 0x000000010eb9c90e _ZN5realm2js10RealmClassINS_4node5TypesEE11constructorEN4Napi3EnvENS5_6ObjectERNS0_9ArgumentsIS3_EE + 334
9 .com.mongodb.realm-studio.xU50Kf 0x000000010eb99289 _ZN5realm4node10ObjectWrapINS_2js10RealmClassINS0_5TypesEEEE20constructor_callbackERKN4Napi12CallbackInfoE + 135
10 .com.mongodb.realm-studio.xU50Kf 0x000000010eb9b8da _ZN5realm4node13WrappedObjectINS_2js10RealmClassINS0_5TypesEEEEC2ERKN4Napi12CallbackInfoE + 128
11 .com.mongodb.realm-studio.xU50Kf 0x000000010eb9b7af _ZZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ENKUlvE_clEv + 67
12 .com.mongodb.realm-studio.xU50Kf 0x000000010eb9b525 _ZN4Napi10ObjectWrapIN5realm4node13WrappedObjectINS1_2js10RealmClassINS2_5TypesEEEEEE26ConstructorCallbackWrapperEP10napi_env__P20napi_callback_info__ + 71
13 Electron Framework 0x00000001087897ca napi_create_function + 858
14 Electron Framework 0x0000000103c362ec _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 16844
15 Electron Framework 0x0000000103c354b8 _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 13208
16 Electron Framework 0x0000000103c34d9f _ZN2v88internal9Accessors12MakeAccessorEPNS0_7IsolateENS0_6HandleINS0_4NameEEEPFvNS_5LocalINS_4NameEEERKNS_20PropertyCallbackInfoINS_5ValueEEEEPFvS9_NS7_ISB_EERKNSA_INS_7BooleanEEEE + 11391
17 Electron Framework 0x0000000104638999 _ZN2v88internal20SetupIsolateDelegate9SetupHeapEPNS0_4HeapE + 501289

**Comment by kraenhansen** [comment]
Thank you for reporting this, I believe I have a pretty good idea on why this is happening.
I'll circle back with an ETA of a fix for this.

**Comment by michaeljajou** [comment]
Current dealing with this issue, any way to go around this?
