### ISSUE TITLE
App icon on Mac is too big?

### ISSUE THREAD

**Issue by wangchou** [realm/realm-studio#1364]
**Describe the bug**
App icon is too big. Borders are not aligned with other apps.
![Screen Shot 0002-12-01 at 6 30 25](https://user-images.githubusercontent.com/32716/100675870-bfc4db00-33a2-11eb-8ce7-dd38673bcf00.jpg)

**To Reproduce**
Install realm studio on mac.

**Expected behavior**
As HCI Guideline said **"Keep primary content within the icon grid bounding box"**
(https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

screenshot from above link
![Screen Shot 0002-12-01 at 6 57 56](https://user-images.githubusercontent.com/32716/100676039-087c9400-33a3-11eb-88c4-84ad959968ea.jpg)

**Versions:**
 - OS: osx 11.0.1
 - Studio Version : 10.0.1
 - Realm Object Server version [e.g. 3.0.1]

**Additional context**

**Comment by kraenhansen** [comment]
Thanks a lot for taking the time to put together this issue.

Pull requests are very welcome: The icon is located here: https://github.com/realm/realm-studio/tree/channel/major-10/resources (I assume we'll have to update the .icns file to fix this)
