### ISSUE TITLE
Realm Studio 10.0.1 fails to open Realm file

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-studio#1365]
**Describe the bug**
Realm Studio 10.0.1 fails to open Realm file created from RealmSwift v4.4.1.  

**To Reproduce**
1. Open realm file created by RealmSwift v4.4.1
2. Select "Upgrade in place"
3. Blank screen appears and stays that way

**Expected behavior**
Expect file to be upgraded to v10.0.1 format

**Screenshots**

**Versions:**
 - OS: macOS 11 / Apple M1 MacBook Air 
 - Studio Version: 10.0.1 (runs under rosetta)
 - Realm Object Server version: N/A

**Additional context**
A workaround seems to be to open the same file with Realm Studio v5.0.1 and upgrade the file format and then open the file with MongoDB Realm Studio v10.0.1.  This appears to work.

**Comment by kneth** [comment]
@duncangroenewald Similar to #1366, can you try to reproduce it in an Intel based Mac?

**Comment by kraenhansen** [comment]
@duncangroenewald please try again with [MongoDB Realm Studio at v10.1.1](https://github.com/realm/realm-studio/releases/tag/v10.1.1), we upgraded dependencies that should now make us M1 SoC compatible.

**Comment by duncangroenewald** [comment]
@kraenhansen - Cool thanks
