### ISSUE TITLE
Must be of type 'string?', got 'number' - import failed due to database features

### ISSUE THREAD

**Issue by derrikF** [realm/realm-studio#1372]
**Versions:**
 - OS: MacOS 10.12 / Linux Mint 20
 - Studio Version - 3.10.1

Hello

I need to import a database into a single MacOS app.

realm opens in Realm Studio-3.10.1, in MongoDB requires an upgrade.

first I need to do an export to view the csv structure, which I was only able to do with Realm Browser 3.0.1

Next, I decided to check whether the macOS app will accept the database I changed.
to do this, I decided to import the csv I just received after exporting, to the same database, deleting the values so that there was no conflict.
Realm Browser 3.0.1 does not import to the same database, but only allows you to create a new database from csv, but The MacOS app does not accept a new database.

then there is only Realm Studio-3.10.1. but it has another problem - it just does not import data, the problem is in the screenshot.

Well, what's the difference that there are numbers for "string", this is not an error, this is a feature of this database.

is it possible to ignore such warnings in Realm Studio-3.10.1? because this is not an error, but Realm Studio-3.10.1 does not allow you to import because of it. MongoDB issues the same warning.

Thanks

![01](https://user-images.githubusercontent.com/4710022/101879604-a726a300-3ba2-11eb-8ebd-bd5e163194c9.png)

**Comment by kneth** [comment]
> first I need to do an export to view the csv structure, which I was only able to do with Realm Browser 3.0.1

If you have relationships (links and/or lists of links), exporting to JSON is better. Most editors today have good support for JSON which can help you when inspecting your file.

> then there is only Realm Studio-3.10.1. but it has another problem - it just does not import data, the problem is in the
> screenshot.
> 
> Well, what's the difference that there are numbers for "string", this is not an error, this is a feature of this database.

I imagine that the importer get confused if a string isn't quoted but looks like a number. Can you share a few lines of your CSV file to see if this is the issue.

> Realm Browser 3.0.1 does not import to the same database

True, we don't support appending to an existing database.

**Comment by derrikF** [comment]
> exporting to JSON is better

me would have been even better but import no from json.

I've tried to quote the numbers, it's still a mistake.

here's the base, here's an example of csv, data in quotes, try the import yourself with 3.10.1, import to _RNCSCItem

[csv.zip](https://github.com/realm/realm-studio/files/5683356/csv.zip)

**Comment by kneth** [comment]
When I import `_RNCSSCItem.csv` the property `startParaID` has the type `double`. For a JavaScript developer, this is not counter-intuitive (`parseFloat("1800.251")` will return a number) and we believe this is the most common use case.

You can write a small node.js script to parse your CSV file (for example using [Papa Parse](https://www.papaparse.com/)) and convert data to the type your schema requires.

**Comment by derrikF** [comment]
Note the error in the screenshot. In csv, the value is "1800.2510", and why in the error "1800.251"? Where did " 0 " go?

The problem is in Realm Studio, it does not process data correctly when there is a dot between the digits.

For a sample, I took instead of a dot put a space "1800 2510" and the data was imported.
I put a space before the dot "1800 .251" and in this case the data was imported.

but when you set "1800.2510", as it should, the data is not imported and the error value is shown without the last zero "1800.251".

What does the Realm Studio? clearly it's HIM...

**Comment by kraenhansen** [comment]
I agree @derrikF we have a bug in Realm Studio here. And it is as you're referring to, Realm Studio infers the type when reading the CSV instead of relying on the schema types when importing into an existing Realm file.

I'm sorry for the confusion here, this is a bug that we should fix.

**Comment by derrikF** [comment]
Doesn't work anyway.

Here is a screenshot of how version 10.1.0 imports - the import goes to the class that I selected, but it gives the error that you were trying to fix.

![10 1 0](https://user-images.githubusercontent.com/4710022/106244300-c1ccde00-621b-11eb-9efe-0ee9f982b28b.png)

and here is how version 10.1.1 does import now into the same database from the same csv https://github.com/realm/realm-studio/issues/1372#issuecomment-743777165

![10 1 1](https://user-images.githubusercontent.com/4710022/106244443-f04ab900-621b-11eb-8799-72cdc3f1d0a0.png)

that is, now it does not want to import at all, because it tries to import not to the class that is selected, but to the first one in the list.

in general, everything was broken...

**Comment by kraenhansen** [comment]
The CSV importer (admittedly not well documented) will import CSV files into classes matching on the filename of the CSV file. So say you have two classes, Person and Dog it's supposed to be able to import Person.csv and Dog.csv respectively. The class focussed from the left sidebar has no effect on where the data is imported to (at least not in its current state).

**Comment by kraenhansen** [comment]
Scrap that - it looks like I introduced another issue while solving this: https://github.com/realm/realm-studio/issues/1389 👎

**Comment by kraenhansen** [comment]
@derrikF sorry for the long wait here. This should be solved in v10.1.2 and v5.0.3, please feel free to open another issue if you (contrary to my expectations) find another issue in with this feature. Thank you again for reporting this and for you patience.

**Comment by derrikF** [comment]
Yes, thanks, imported successfully.
