### ISSUE TITLE
CSV Import - Imports to class, not subclass

### ISSUE THREAD

**Issue by timothystulman** [realm/realm-studio#1389]
**Describe the bug**

On the newest version of Realm Studio, when I click "Import from CSV", the items appear in the superclass instead of the subclass. 

**To Reproduce**
1. Create a class and then subclass in a realm database. 
(For me, the superclass is "Card" and I have various types of cards.)

2. From Realm Studio, go to Import Data From... CSV. Select a CSV file with a name that matches the subclass. The data will be imported into the superclass and not the subclass. 
(In prior versions, I'd select the CSV with the file name that corresponds to my subclass and select import. All data would then be imported into the subclass. Now, regardless of the name of the CSV, the data goes to the superclass and data from the properties specific to my subclasses is lost. 

**Expected behavior**
I expected the data to be imported into the subclass, as was the case in prior versions. 

**Screenshots**

See attached. 
-"Old Version" shows the correct import into Notes (subclass). 
-"New Version" shows the incorrect import into Card (superclass). 

**Versions:**
 - OS: 11.0.1
 - Studio Version:  10.1.1
 - Realm Object Server version [e.g. 3.0.1]

**Additional context**
<img width="1219" alt="On new version" src="https://user-images.githubusercontent.com/61549171/106197112-44a05b00-6180-11eb-9cd2-2bb69575c77c.png">
<img width="1232" alt="On old version" src="https://user-images.githubusercontent.com/61549171/106197117-45d18800-6180-11eb-88d1-ac7f11b1b201.png">

**Comment by kraenhansen** [comment]
What is the name of the file you're importing from? Isn't it the case that file named `Note.csv` will get imported as Note objects?

**Comment by kraenhansen** [comment]
Thanks for reporting this, I believe I understand the root cause of this.
For now you'll have to use the previous version of Studio.

**Comment by timothystulman** [comment]
Thank you, Kræn!

**Comment by kraenhansen** [comment]
@timothystulman This should be solved in v10.1.2 and v5.0.3, please reopen if the issue persists.
