### ISSUE TITLE
Import Data from > CSV can't import a boolean

### ISSUE THREAD

**Issue by misthupper** [realm/realm-studio#1396]
It is not possible to import data from a csv-file into the realm. I tried with different entries like TRUE, 'TRUE', false, 1 ...

**To Reproduce**
1. use a model with a boolean column
2. Click on 'Import Data from > CSV'

**Screenshots**
<img width="290" alt="Screenshot 2021-02-16 at 16 32 13" src="https://user-images.githubusercontent.com/2051791/108085003-263dc900-7075-11eb-9162-35fbe6eeabb8.png">

**Versions:**
 - MacOs 11.2.1
 - Realm Studio 10.1.1

**Comment by kraenhansen** [comment]
Be believe this will be fixed as soon as this gets merged and released: https://github.com/realm/realm-studio/pull/1392

**Comment by kraenhansen** [comment]
This should be solved in v10.1.2 and v5.0.3, please reopen if the issue persists.
