### ISSUE TITLE
Can't open files without .realm extension

### ISSUE THREAD

**Issue by szkabaroli** [realm/realm-studio#1409]
**Describe the bug**
Hi! My issue is that Realm Studio only allows to open files with the .realm extension. This prevent me from open realm files without or with different file extension. 

**To Reproduce**
Try to open a db file without .realm file extension.

**Expected behavior**
I expect a second filter option in the file open dialog that allows me to open files with any extension.

**Versions:**
 - OS: Ubuntu 20.04
 - Studio Version 10.1.2

**Comment by szkabaroli** [comment]
#1410

**Comment by szkabaroli** [comment]
Resolved.

**Comment by steffenagger** [comment]
> #1410

Thanks for contributing @szkabaroli 🙏
