### ISSUE TITLE
[add title here] (Sentry ID: ef8682edca914de2a7a1988d9387b86e)

### ISSUE THREAD

**Issue by AppleDP** [realm/realm-studio#1425]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Versions:**
 - OS: [e.g. Mac/Windows/]
 - Studio Version [e.g. 2.0.0]
 - Realm Object Server version [e.g. 3.0.1]

**Additional context**

**Comment by kraenhansen** [comment]
Please fill out the template above :)
