### ISSUE TITLE
Mongo DB Realm Studio doesn’t open realm file

### ISSUE THREAD

**Issue by AvelinoJavier** [realm/realm-studio#1433]
**Describe the bug**
Mongo DB Realm Studio 11.0.0-beta.1 doesn’t open realm file created in Android studio in windows 10.

**To Reproduce**
1. Download realm file from device file explorer from android studio.
2. Open Realm file
3. Realm window opened but without data.

**Expected behavior**
Show data in realm file.

**Screenshots**
![image](https://user-images.githubusercontent.com/10343751/121384458-49d39a80-c916-11eb-980f-0a239b6f8929.png)

**Versions:**
 - OS: Windows 10
 - Studio Version standalone 11.0.0-beta.1
 - io.realm:realm-gradle-plugin:10.4.0

**Comment by takameyer** [comment]
Thanks for reporting!  There seems to be an issue with the Windows version of Realm Studio.  We will look into this as soon as we can.

**Comment by larnor** [comment]
Also related, the linked "demo-v20.realm" from the splash screen cannot be opened. Same white screen. (Windows 10,  Realm Studio 11.0.0-beta.1)

**Comment by akashthakkar09** [comment]
Describe the bug
Mongo DB Realm Studio 11.0.0-beta.1 doesn’t open realm file created in XCode 12.5 with macOS 11.3.1

<img width="1912" alt="Screenshot 2021-06-17 at 5 46 41 PM" src="https://user-images.githubusercontent.com/8245561/122394847-091df600-cf94-11eb-9a50-4e4efd85cede.png">

**Comment by kneth** [comment]
Please see https://github.com/realm/realm-studio/issues/1434#issuecomment-863908434

**Comment by kraenhansen** [comment]
MongoDB Realm Studio v11.0.0 has now been released, with support for the v22 file format, please upgrade and reopen if the issue persists

**Comment by akashthakkar09** [comment]
@kraenhansen Thanks for the update I have upgraded the new version v11.0.0 and its working fine with the v22 file formate.
