### ISSUE TITLE
Browsing the realm database generated using Realm v10.8.0 fails

### ISSUE THREAD

**Issue by ravikirankhareedi** [realm/realm-studio#1434]
**Describe the bug**
Opening realm files throws an error - "Realm files of format version 22 is not supported by this version of Realm."
Realm Studio Version 11.0.0-beta.1
Realm v10.8.0

**To Reproduce**
Use Realm v10.8.0 with a swift application. Make use of the new feature, AnyRealmValue. Write to the DB. Try opening the file with the above mentioned version of Realm Studio.  

**Expected behavior**
As per the doc, Realm Studio Version 11.0.0-beta.1 should be compatible. 

**Screenshots**
<img width="827" alt="Screen Shot 2021-06-15 at 21 00 34" src="https://user-images.githubusercontent.com/7555400/122108658-bd950c00-ce1c-11eb-87a6-e1837baef29b.png">

**Versions:**
 - OS: Mac 11.1
 - Studio Version: Realm Studio Version 11.0.0-beta.1
 - Realm Object Server version [e.g. 3.0.1]

**Comment by kneth** [comment]
@ravikirankhareedi Unfortunately we haven't released Realm Studio with support for the new data types (and the new file format). We are currently working on getting a version of Realm JavaScript release with support for new file format. Realm Studio will be upgraded and released shortly after.

**Comment by tomcondon** [comment]
It seems irresponsible to release a new file format without a tool that can read it. Looking at data in your database independent of your app being developed is a pretty vital feature. As I am finding out this Father's day this Sunday night.

**Comment by ravikirankhareedi** [comment]
> @ravikirankhareedi Unfortunately we haven't released Realm Studio with support for the new data types (and the new file format). We are currently working on getting a version of Realm JavaScript release with support for new file format. Realm Studio will be upgraded and released shortly after.

Thanks for the update. Can you please update the documentation accordingly. Thanks.

**Comment by ianpward** [comment]
@tomcondon We had planned for RealmJS to be released with the other SDKs but the engineer responsible for performing the release was hit by a personal emergency. Thank you for your support of this free and open source project.

**Comment by ndav** [comment]
It’s unfortunate that this has happened but we are where we are. I have literally just started using realm and though it was me. Glad I found this thread. I would say from an engineering perspective it would have been better to hold off on the library update until the tools were ready to support it. 

Not particularly helpful comments on this being a free library. Essentially telling us to shut up or put up. Developer relations are way more important than a simple issue (especially now with MongoDB in the fray). Let’s move past it but I would suggest a little more comms to those using the library to make this the community you’d want it to be.

**Comment by ianpward** [comment]
I am just hoping that we can all have some patience and remember that we are humans that have other things occur in our lives. We couldn't have held back the release because the other releases were out already when the issue with JS occurred, but I'm not sure we would have held the other releases anyway since Studio is in use by less than 10% of our users. Other users develop their own ways to view the database such as print the object in question to console or develop their own command-line utility. I myself find Studio useful for development - but if you're in development and you really need to use Studio, why not downgrade to a version that supports Studio to continue your development?

**Comment by ndav** [comment]
Just to clarify this issue exists in swift/iOS too (not just JS). This was the basis of the initial issue report.

**Comment by ianpward** [comment]
Studio is built with RealmJS which is dependency to build a new version.

**Comment by ndav** [comment]
> Studio is built with RealmJS which is dependency to build a new version.

Aha got you 👍

**Comment by yuya-h-29** [comment]
@ndav @kneth @ravikirankhareedi 
Hi, I'm new to iOS dev and Realm database.
So... I came across this issue now. (Realm files of format version 22 is not supported by this version of Realm.)
I understood it is not possible to browse the data in the format currently, but how can I change the format version to browse data in Realm Studio??

**Comment by FelixLisczyk** [comment]
@yuya-h-29 You need to use an older version of the Realm framework, e.g. [v10.7.7](https://github.com/realm/realm-cocoa/releases/tag/v10.7.7). This approach only works if you haven't shipped your app with the new Realm framework yet. Downgrading an existing database will crash the app on launch.

**Comment by yuya-h-29** [comment]
@FelixLisczyk 
Thank you for the reply!
I wrote `  pod 'RealmSwift', '~> 10.7.7'` in my project and copy and pase the url of `/Users/... /default.realm` to Realm Studio, but still get the same message...

**Comment by yuya-h-29** [comment]
@FelixLisczyk
I downgraded to '10.7.3' and now it is working...
Thank you for your help!!

**Comment by bhagyash007** [comment]
Extremely unprofessional and a bad developer experience. Mongo realm is a commercial product which developers are expected to trust their entire database architecture on. Blaming it on the lead engineers personal circumstance is even worse, you're saying that the entire engineering division of a publicly traded company can't fix this?
Mentioning statistics like less than 10% is just another poor excuse doesn't raise belief.
Highly skeptical of using the service.

**Comment by ianpward** [comment]
Realm Studio v11 has been released with support for file format v22 - 
https://studio-releases.realm.io/v11.0.0
