### ISSUE TITLE
Version 11.0.0 fails to open synced Realms

### ISSUE THREAD

**Issue by luigidegiacomo** [realm/realm-studio#1438]
**Describe the bug**
Version 11.0.0 Mac not open file create with realm-dotnet 10.2.0

**To Reproduce**
1. Sync a realm with 10.2.0 of dotnet
2. Go To mongodb-realm folder
3. Open file .realm

**Expected behavior**
error is: Options 'disableFormatUpgrade' and 'sync' are mutual exclusive.
**Screenshots**

**Versions:**
 - OS: [Mac BigSur 11.4]
 - Studio Version [e.g. 11.0.0]
 - Realm Object Server version [e.g. 10.2.0]

<img width="866" alt="Schermata 2021-06-27 alle 01 28 05" src="https://user-images.githubusercontent.com/38740910/123528389-ee135a80-d6e6-11eb-86a1-864805198aa5.png">

**Comment by kneth** [comment]
Please upgrade to Realm Studio v11.0.1.

**Comment by luigidegiacomo** [comment]
Sorry, same error with v11.0.1
I don't open realm file with studio, but it's works fine with DotNet Application with Realm 10.2.1

**Comment by moilotus** [comment]
I'm seeing the same. macOS with v11.0.1, .net app running 10.2.0, but I have also tried 10.5.0-alpha.541.

.net app runs fine. When I try to open the realm with Realm Studio, I get the exact same image in the first post on this thread.

Thanks.

**Comment by kraenhansen** [comment]
Still need to upgrade Realm JS and publish a release.
