### ISSUE TITLE
Viewing Table with Relationships Hangs on macOS

### ISSUE THREAD

**Issue by VaslD** [realm/realm-studio#1451]
**Describe the bug**

I'm working with about 5 different models in .NET and some of them are linked with `IList<T>` declarations.

After writing data to a local file, I can get back expected properties and relationships if I read in .NET, but when I open this file in Realm Studio, switching to any "table" with relationships hangs the app.

**To Reproduce**

1. Download the attachment.
2. Load this file in Realm Studio.
3. Switch "Classes". The app will freeze after switching to Time Zone or Region.

**Expected behavior**

The table of specified class loads without issue. And generates an intermediate table when I traverse to related models as seen on Windows.

**Screenshots**

I don't think screenshot helps to illustrate hang 😃 

**Versions:**

 - OS: macOS 11.6 (20G165)
 - Studio Version: 11.1.0

**Additional context**

The attached file is generated from some IANA Time Zone database with added relationships between models.

[Time Zones.realm.zip](https://github.com/realm/realm-studio/files/7166397/Time.Zones.realm.zip)

**Comment by kneth** [comment]
I can reproduce it using MongoDB Realm Studio 11.1.0 and the attached Realm file. Moreover, I observe a big CPU load.

Furthermore, I have opened the file using node.js. By inspecting the schema and the objects, I see cycles in the object graph. We need to investigate if cycles can lead Studio to hang (and it can explain the observed CPU load).

**Comment by VaslD** [comment]
> I can reproduce it using MongoDB Realm Studio 11.1.0 and the attached Realm file. Moreover, I observe a big CPU load.
> 
> Furthermore, I have opened the file using node.js. By inspecting the schema and the objects, I see cycles in the object graph. We need to investigate if cycles can lead Studio to hang (and it can explain the observed CPU load).

Are cycles allowed in Realm? Now you mentioned it I actually never created any Realm that had cycles before. Normally I'd use `[Backlink]`s, but I need to debug this Realm in Studio so I intentionally converted all `[Backlink]`s to references because `[Backlink]`s do not show in Studio.

**Comment by kraenhansen** [comment]
> Are cycles allowed in Realm?

Yes they are and Studio should definitely support that use-case.

For reference, the schema of the Realm is:

```json
[
  {
    "name": "City",
    "properties": {
      "Continent": {
        "name": "Continent",
        "type": "object",
        "objectType": "Continent",
        "indexed": false,
        "optional": true,
        "mapTo": "Continent"
      },
      "Region": {
        "name": "Region",
        "type": "object",
        "objectType": "Region",
        "indexed": false,
        "optional": true,
        "mapTo": "Region"
      },
      "Name": {
        "name": "Name",
        "type": "string",
        "indexed": false,
        "optional": true,
        "mapTo": "Name"
      },
      "TimeZone": {
        "name": "TimeZone",
        "type": "object",
        "objectType": "Time Zone",
        "indexed": false,
        "optional": true,
        "mapTo": "TimeZone"
      }
    },
    "embedded": false
  },
  {
    "name": "Continent",
    "properties": {
      "ID": {
        "name": "ID",
        "type": "string",
        "indexed": true,
        "optional": true,
        "mapTo": "ID"
      },
      "Name": {
        "name": "Name",
        "type": "string",
        "indexed": true,
        "optional": true,
        "mapTo": "Name"
      },
      "MajorCities": {
        "name": "MajorCities",
        "type": "list",
        "objectType": "City",
        "indexed": false,
        "optional": false,
        "mapTo": "MajorCities"
      }
    },
    "primaryKey": "ID",
    "embedded": false
  },
  {
    "name": "IANA Time Zone",
    "properties": {
      "ID": {
        "name": "ID",
        "type": "string",
        "indexed": true,
        "optional": true,
        "mapTo": "ID"
      },
      "TimeZone": {
        "name": "TimeZone",
        "type": "object",
        "objectType": "Time Zone",
        "indexed": false,
        "optional": true,
        "mapTo": "TimeZone"
      }
    },
    "primaryKey": "ID",
    "embedded": false
  },
  {
    "name": "Region",
    "properties": {
      "ID": {
        "name": "ID",
        "type": "string",
        "indexed": true,
        "optional": true,
        "mapTo": "ID"
      },
      "Name": {
        "name": "Name",
        "type": "string",
        "indexed": false,
        "optional": true,
        "mapTo": "Name"
      },
      "MajorCities": {
        "name": "MajorCities",
        "type": "list",
        "objectType": "City",
        "indexed": false,
        "optional": false,
        "mapTo": "MajorCities"
      }
    },
    "primaryKey": "ID",
    "embedded": false
  },
  {
    "name": "Time Zone",
    "properties": {
      "Name": {
        "name": "Name",
        "type": "string",
        "indexed": true,
        "optional": true,
        "mapTo": "Name"
      },
      "OffsetInMinutes": {
        "name": "OffsetInMinutes",
        "type": "int",
        "indexed": true,
        "optional": false,
        "mapTo": "OffsetInMinutes"
      },
      "Abbreviation": {
        "name": "Abbreviation",
        "type": "string",
        "indexed": false,
        "optional": true,
        "mapTo": "Abbreviation"
      },
      "MajorCities": {
        "name": "MajorCities",
        "type": "list",
        "objectType": "City",
        "indexed": false,
        "optional": false,
        "mapTo": "MajorCities"
      }
    },
    "primaryKey": "Name",
    "embedded": false
  }
]
```

**Comment by kraenhansen** [comment]
This got solved by https://github.com/realm/realm-studio/pull/1452. We're still missing a release.
