### ISSUE TITLE
How do you filter on a uuid?

### ISSUE THREAD

**Issue by gbreen12** [realm/realm-studio#1457]
I've tried everything I know how to and I can't figure it out. I have a simple query 
```
operationalItemID = 'aecfe463-b0ed-489b-a4ae-2f19c3d2e5fd'
``` 
but it says "unsupported comparison between type 'uuid' and type 'string'". operationalItemID is a uuid in this example.

Is this possible in the current version?

**Comment by kraenhansen** [comment]
You should be able to use:

```
operationalItemID = uuid(aecfe463-b0ed-489b-a4ae-2f19c3d2e5fd)
```

**Comment by gbreen12** [comment]
Yes! That works. Is that documented somewhere that I missed?

**Comment by kneth** [comment]
No, you didn't miss it - we did. We must add how to query uuid (and objectId) to https://docs.mongodb.com/realm/sdk/node/advanced/query-engine/#std-label-node-client-query-engine
