### ISSUE TITLE
Unable to connect to MongoDB Realm App - is this possible ?

### ISSUE THREAD

**Issue by duncangroenewald** [realm/realm-studio#1462]
**Describe the bug**
Not entirely sure this is a bug but does "Log in to Realm Cloud" work and if so does this log in to MongoDB Realm App or to Atlas ?

Perhaps I am confused but I was sure this allows connection to a MongoDB Realm App.  Now it seems to reject any email/password combination.

It has been a while since we tried using Realm Studio, so recollection is a bit hazy as to what it supports.  As usual the documentation is extremely poor and references to Realm Cloud is confusing since that is what the legacy Realm Cloud service is called.

Thanks for providing clarity over this.

**Comment by tomduncalf** [comment]
As of Realm Studio v10, the "Log in to Realm Cloud" option has been removed, so you may be using an outdated version. 

If you would like to manage data stored in MongoDB Atlas, [MongoDB Compass](https://www.mongodb.com/products/compass) provides a GUI tool for doing so.
