### ISSUE TITLE
11.0 Lags 

### ISSUE THREAD

**Issue by raphaels17** [realm/realm-studio#1463]
**Describe the bug**
I have tested on a numerous db the last version simply does allow to visualise data and lags terribly :-/
should I downgrade my version ?

**To Reproduce**
open the file try to access the table ticket ... and wait forever

**Expected behavior**
be able to navigate on the db smoothly

**Versions:**
 - OS: Mac
 - Studio Version 11.1.0
 - Realm Object Server version NA

[db-15854-11889-2.realm.zip](https://github.com/realm/realm-studio/files/7636387/db-15854-11889-2.realm.zip)

**Comment by tomduncalf** [comment]
@raphaels17 Realm Studio v11.1.1 is now out: https://github.com/realm/realm-studio/releases/tag/v11.1.1. Could you let me know if that improves things for you?

**Comment by raphaels17** [comment]
YES it changed drastically . Great job!  





On Mon, Dec 6, 2021 at 5:58 PM Tom Duncalf ***@***.***>  wrote:


@raphaels17  Realm Studio v11.1.1 is now out: 
https://github.com/realm/realm-studio/releases/tag/v11.1.1. Could you let me
know if that improves things for you?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS  or Android. 



***@***.***+33 6 22 81 33 33
84 Boulevard Georges Seurat| 92200 Neuilly-Sur-Seine, France

**Comment by tomduncalf** [comment]
I'm happy to hear it helped!
