### ISSUE TITLE
Error occurred while updating

### ISSUE THREAD

**Issue by carbonete** [realm/realm-studio#1470]
**Describe the bug**
Unsuccessful update because certificate is missing.

**To Reproduce**
1. Open Realm Studio 
2. Click on Yes in update pop-up 
3. See error

**Expected behavior**
Update occur 

**Screenshots**

![image](https://user-images.githubusercontent.com/3043885/147659674-a0ea6504-ba67-4b6f-ab13-de07700c8b51.png)

**Versions:**
 - OS:  Windows 10
 - Studio Version 11.1.0

**Comment by kraenhansen** [comment]
Thanks a lot for reporting this. It does indeed look like the 11.1.0 release got signed with an expired certificate. We'll get a new version out first thing in the new year. Until then, you can download the previous version here on GitHub: https://github.com/realm/realm-studio/releases/tag/v11.1.0

**Comment by carbonete** [comment]
@kraenhansen thanks, i have v11.1.0 installed and try update it click in update button.

**Comment by Jaycyn** [comment]
@kraenhansen

I think the OP attempted to download 11.1.1 which is the issue, not 11.1.0. Which one has the expired certificate?

**Comment by carbonete** [comment]
Maybe not expired but signed with different owner. Error windows have two messages 

1 - New version 11.1.1 is not signed by the application owner 
2 - StatusMessage : "A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file"

**Comment by fronck** [comment]
@carbonete Thanks for the update.  We'll get a properly-signed version released first thing in the new year.

**Comment by kraenhansen** [comment]
We resigned and uploaded the new signed binaries for the 11.1.1 release: Please restart your MongoDB Realm Studio to allow the auto-update to look for a new version. Downloading and restarting the app should now work as expected.

Thanks again for reporting this!
