### ISSUE TITLE
Missing assets on 11.1.1 release page

### ISSUE THREAD

**Issue by gongzhang** [realm/realm-studio#1472]
**Describe the bug**

Hi, Realm Studio Team,

I noticed that the [11.1.1 release page](https://github.com/realm/realm-studio/releases/tag/v11.1.1) does not come with the installation files for each platform as usual. Only the default source code zip file is available. It breaks installation commands like `brew install 'mongodb-realm-studio'`.

```log
Error: Download failed on Cask 'mongodb-realm-studio' with message: Download failed: https://github.com/realm/realm-studio/releases/download/v11.1.1/MongoDB.Realm.Studio-11.1.1.dmg
```

Could you please add the installation packages like before?

```
MongoDB.Realm.Studio-x.x.x-mac.zip
MongoDB.Realm.Studio-x.x.x-win.zip
MongoDB.Realm.Studio-x.x.x.AppImage
MongoDB.Realm.Studio-x.x.x.dmg
MongoDB.Realm.Studio.x.x.x.exe
MongoDB.Realm.Studio.Setup.x.x.x.exe
```

Thanks.

**To Reproduce**
1. Run `brew install 'mongodb-realm-studio'` on macOS

**Versions:**
 - OS: macOS

**Comment by kraenhansen** [comment]
Thanks for reporting this! We had an issue with Windows binaries being signed with an expired certificate, so we had to republish the binaries. Unfortunately the new GitHub release ended up in draft-mode. I've corrected this and the files should now be available.
