### ISSUE TITLE
"LockFileEx() failed" error when opening .realm on Windows via WSL

### ISSUE THREAD

**Issue by vamjam** [realm/realm-studio#1477]
**Describe the bug**
If I attempt to open a database in Realm Studio that lives on the WSL instance, I get an error: 
```
LockFileEx() failed: Incorrect function.
```
and
```
"No schema selected"
```

This happens with both "File open" and double-clicking the file.

**To Reproduce**
1. Create a realm file in a WSL instance
2. Try and open it
3. See error

**Expected behavior**
If I copy the .realm file to the Windows file system, it opens just fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/95667325/153796510-607ab524-28f2-458e-bf59-906fecf50fbf.png)

**Versions:**
 - OS: Ubuntu 20.04.3 LTS on Windows 11 via WSL (2)
 - Studio Version: 11.1.1
 - Realm Object Server version [e.g. 3.0.1] <-- never heard of it

**Additional context**
I also tried opening it when it wasn't in use, same result.

**Comment by kraenhansen** [comment]
Thanks for reporting this. In all honesty, this is not something we test for.
Realm Core (the C++ library that Realm Studio uses when opening the database file) uses a syscall to lock the database file [which doesn't seem to be implemented on WSL2](https://github.com/microsoft/WSL/issues/5762). We'd have to detect this and perhaps disable some features (most likely opening a Realm from multiple processes) to fix this.

I've created [an issue in Realm Core](https://github.com/realm/realm-core/issues/5258) and added it to our backlog, but I can't say when this will be fixed. For the time being I'm afraid you'll have to copy the file to your regular filesystem before opening.

**Comment by vamjam** [comment]
Was playing around with this again, and as an FYI for anyone else that may stumble on this - installing Realm Studio for Linux on the WSL 2 distro works great. (Most) Linux GUI apps just work in WSL 2, including Realm Studio. Nifty.

**Comment by kraenhansen** [comment]
That's a great workaround. 
Thanks for circling back and sharing it. 👍
