### ISSUE TITLE
[add title here] (Sentry ID: 84d5e20afde04711b29be86eb86521bf)

### ISSUE THREAD

**Issue by Mixast** [realm/realm-studio#1480]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Versions:**
 - OS: [e.g. Mac/Windows/]
 - Studio Version [e.g. 2.0.0]

**Additional context**

**Comment by kraenhansen** [comment]
Please fill in the template and reopen.
