### ISSUE TITLE
I couldn't download Realm Studio

### ISSUE THREAD

**Issue by MuratAkbaba006** [realm/realm-studio#1512]
**Describe the bug**
I couldn't download Realm Studio

**To Reproduce**
1. Go to https://www.mongodb.com/docs/realm-legacy/products/realm-studio.html#download-studio
2. Click on Download for mac
3. See error

**Expected behavior**
i should be able to download realm studio

**Screenshots**
<img width="1188" alt="Screen Shot 2022-06-06 at 09 33 42" src="https://user-images.githubusercontent.com/44754934/172108102-a4409a01-e643-49df-ba69-070e2c512d9f.png">

**Comment by liamjones** [comment]
Firefox states the error slightly differently if it helps: `SSL_ERROR_NO_CYPHER_OVERLAP`

**Comment by liamjones** [comment]
@MuratAkbaba006 if you're not aware, you can also grab it from the releases page here: https://github.com/realm/realm-studio/releases

**Comment by takameyer** [comment]
@MuratAkbaba006 Thanks for reporting.  We'll look into this right away

**Comment by kraenhansen** [comment]
@MuratAkbaba006 the issue is resolved now.
We're really sorry for the inconvenience on this one and I hope your future with Realm and Realm Studio will be a lot smoother from hereon.
