### ISSUE TITLE
Check for updates doesn't find 12.0.0?

### ISSUE THREAD

**Issue by liamjones** [realm/realm-studio#1516]
**Describe the bug**
Realm Studio 11.2.1 doesn't prompt that v12.0.0 is out, it believes it's the latest version of the app - not sure if this is deliberate?

**To Reproduce**
1. Install 11.2.1
2. 'Check for updates' from menu
3. See 'This is the latest version'

**Expected behavior**
Prompt to upgrade to 12.0.0

**Versions:**
 - OS: Mac
 - Studio Version: 11.2.1

**Comment by tomduncalf** [comment]
Thanks for the report @liamjones, we're looking into this!

**Comment by tomduncalf** [comment]
Actually this is deliberate as we don't want to break users workflows by upgrading across major versions. We are tracking https://github.com/realm/realm-studio/issues/1455 to implement a separate prompt for major version upgrades but for now it is a manual process.

**Comment by liamjones** [comment]
Gotcha, thanks for the confirmation. (Sorry, I should've searched the existing issues better before raising a new one!)

**Comment by tomduncalf** [comment]
No worries at all, I also didn't know it worked this way until I investigated :)
