### ISSUE TITLE
Incompatible lock file format version 13

### ISSUE THREAD

**Issue by kct3937** [realm/realm-studio#1553]
**Describe the bug**
Cannot open Realm File created in version 12 with version 13.  Error is enclosed in screenshot.

**To Reproduce**

1. Click on '....'
1. See error

**Expected behavior**

**Screenshots**

**Versions:**

* OS: [e.g. Mac/Windows/]
* Studio Version [e.g. 2.0.0]

**Additional context**
![Screen Shot 2022-11-29 at 9 31 05 AM](https://user-images.githubusercontent.com/7966583/204601580-f2500a6e-dea4-44e7-b7b3-48b840f4bd53.png)

**Comment by kneth** [comment]
As the error message indicates, you have the Realm file opened by another process. The other process is using an older version, and that is not supported. You either have to upgrade your SDK (used by the other process) or use an older version of Realm Studio.

**Comment by kct3937** [comment]
It appears that the other process is the Simulator.  I cannot find a way to
upgrade the Simulator alone.  What would you suggest??  This never happened
in previous versions.
Do I need to wipe out my Realm Swift installation and start from scratch?

**Comment by kct3937** [comment]
Now I am getting another error that I have never seen before and in code
that ran fine until I upgraded Realm and realm Studio, so I don't know
which part is causing the error.

Here is a screenshot of the error and one with the init routine behind it
which occurs in the realm init with a named file.

**Comment by kneth** [comment]
I will suggest that you install Realm Studio 12 as Realm Swift hasn't released a version with the new file format.

**Comment by kct3937** [comment]
Thank you, I have done that.  It should also be noted that each time Realm
Studio starts it asks if the user wants to upgrade.  The answer should be
NO...definitely NO or ABSOLUTELY NO if possible.
It seems irresponsible to me to issue an upgrade to one part of the pair
without making sure that the other has all the necessary improvements...but
then I would get fired if I allowed that to happen in my workplace.

**Comment by ianpward** [comment]
hey @kct3937 Product for Realm here. We've gone ahead and removed the tag for the latest version of studio from the update channel so you should stop being prompted to upgrade Studio now. You can manually find the v12 version here and install to ensure compatibility with RealmSwift - https://studio-releases.realm.io/

We apologize for that but we had to revert the other SDK releases while we squashed some bugs but we forgot to remove the update channel tag. 

Thanks for using Realm and have a great day!

**Comment by kct3937** [comment]
Thank you!
