### ISSUE TITLE
Upgrade to v.13 fails with checksum mismatch

### ISSUE THREAD

**Issue by christopher-lawrence** [realm/realm-studio#1554]
**Describe the bug**
Attempting to upgrade to v.13.0.0 gives a checksum mismatch (see screenshot)

**To Reproduce**
1. Click 'Yes' to upgrade to latest version (13.0.0)
2. Allow the download to finish and auto update
3. See error

**Expected behavior**
Realm Studio upgrades successfully.

**Screenshots**
<img width="707" alt="image" src="https://user-images.githubusercontent.com/2027400/205729750-023bd641-365e-4ad8-9ecc-f9113e0f30ec.png">

**Versions:**
 - OS: macOS 13.0.1
 - Chip: Apple M1 Pro
 - Studio Version 12.0.0

**Comment by kneth** [comment]
@christopher-lawrence Thank you for reporting. We are able to reproduce it, and we will make a patch release in order to fix the checksum.

**Comment by kneth** [comment]
@christopher-lawrence It has been fixed, and you should be able to upgrade to version 13.0.2. Please notice that your SDK must support the new file format, and to my knowledge only Realm JavaScript does that. The other SDKs will follow in the near future.
