### ISSUE TITLE
Fails to detect current version and updates

### ISSUE THREAD

**Issue by BlueCobold** [realm/realm-studio#1555]
**Describe the bug**
I am using Realm Studio 11.2.1. The startup-screen says this is the latest version. Making an update-check does not find any new version. When checking here in github, I can see a v12.0.0 changelog and a v13.0.0 release version.

**To Reproduce**
Open RealmStudio, check the displayed version

**Expected behavior**
I expect RealmStudio to tell me that there are updates available

**Screenshots**
![](https://user-images.githubusercontent.com/4488101/206133234-f8f920ec-f2b8-4020-928f-7c0bbaf9a99f.png)

**Versions:**

* OS: macOS Montery 12.6
* Apple Silicone M1 chipset
* Studio Version 11.2.1

**Comment by kneth** [comment]
This is deliberate as we don't want to break users workflows by upgrading across major versions. We are tracking https://github.com/realm/realm-studio/issues/1455 to implement a separate prompt for major version upgrades but for now it is a manual process.

**Comment by BlueCobold** [comment]
Well, it should at least tell me there is a new version available, even if I have to check requirements/consequences and update manually.

**Comment by kneth** [comment]
We have released v13.0.2
