### ISSUE TITLE
Mac OS Ventura 13.2, Realm studio screen blank

### ISSUE THREAD

**Issue by ravishaan27** [realm/realm-studio#1566]
**Describe the bug**
Realm Studio 13.0.2.20, launches, but the screen doesn't get rendered. I can still see that the objects are there when I hover the mouse around, and it even opens up the "Open File dialog", but the main screen doesn't render correctly. I am running Mac OS 13.2.1 on VMWare.

**To Reproduce**
Open Realm studio on Ventura 13.2.1 on VMWare

**Expected behavior**
App screen renders correclty

**Screenshots**
![image](https://user-images.githubusercontent.com/7463393/230172947-168b1932-db84-465e-b2d0-7d19c8664064.png)

**Versions:**

* OS: Mac OS Ventura 13.2.1
* Studio Version - 13.0.2

**Comment by kraenhansen** [comment]
I tried, but failed to reproduce this on my M1 running Ventura 13.3 (22E252).

<img width="1036" alt="Screenshot 2023-04-05 at 20 38 54" src="https://user-images.githubusercontent.com/1243959/230174566-49f46e00-b239-4c96-b150-7844c14df65c.png">

If you're trying to open a specific file, would it be possible for you to share that?

Did this work with other / older versions of Mac OS?

**Comment by ravishaan27** [comment]
I am running it on VMWare on a windows Host machine. The Guest OS is Ventura 13.2
I haven't tested it on any other versions, but it does work on my Windows desktop though.

I have the latest version VMWare

**Comment by kneth** [comment]
@ravishaan27 We have just released v14.0.0, and I am curious to hear if you observe the same behaviour with that version.

**Comment by ravishaan27** [comment]
Its working with 14.0.
Not sure what the issue was, but it seems to have resolved. Thanks.

**Comment by kraenhansen** [comment]
Awesome! We upgraded Electron to the latest major version as part of the v14 release, so this might have been enough to solve this 👍
