### ISSUE TITLE
Unable to open encrypted realm in Macos

### ISSUE THREAD

**Issue by m-amirqushairi-jais** [realm/realm-studio#1571]
**Describe the bug**
Unable to open encrypted realm in Macos. Usually it will appear like a modal popup where you can enter the encryption key but right now it straight away show an error.

**To Reproduce**
1. Open Realm Studio and open any encrypted realm you have
2. And later you will see an error

**Screenshots**
If applicable, 
![Screenshot 2023-04-20 at 10 52 01 AM](https://user-images.githubusercontent.com/96907406/233246895-f350953c-402f-4fed-b71b-0b54307d99f7.jpg)

**Versions:**
 - OS: Mac
 - Studio Version: 14.0.0

**Comment by kneth** [comment]
@m-amirqushairi-jais Thank you for reporting. We have identified where the bug is (see https://github.com/realm/realm-studio/pull/1572 for details), and we will shortly release a patch.

**Comment by kneth** [comment]
@m-amirqushairi-jais We have released v14.0.1 with a fix

**Comment by m-amirqushairi-jais** [comment]
@kneth Okay thank you. I will check it out
