### ISSUE TITLE
Cannot open realm Sync Local File generated by Emulator

### ISSUE THREAD

**Issue by sithu-aung** [realm/realm-studio#1574]
In opening realm file in Realm Studio, it said - 
" Realm file at path '/Users/sithuaung/Library/Developer/CoreSimulator/Devices/A1A75638-22B2-45E2-9878-03F4C708727C/data/Containers/Data/Application/5219EE8A-FABB-430C-9B0B-C11BDCE31F3B/Documents/mongodb-realm/pos-altxs/644631daf6b73c4987ea621a/default.realm' has history type 'SyncClient', but is being opened in local history mode. Synchronized Realms cannot be opened in non-sync mode, and vice versa. "

I am using latest version of realm studio V 14.0.1. Please let me know how to proceed with sync mode.

**Comment by kneth** [comment]
@sithu-aung Thank you for reporting. We have a fix in #1575
