### ISSUE TITLE
Database upgrade required but prohibited

### ISSUE THREAD

**Issue by robertnicjoo** [realm/realm-studio#1577]
**Describe the bug**
I just installed latest version and I cannot open my database files anymore.

**To Reproduce**

1. Open realm file `abcd.realm`
1. See error `Database upgrade required but prohibited`

**Expected behavior**
File to be opened!

**Screenshots**
![Screenshot 2023-05-02 at 13 27 22](https://user-images.githubusercontent.com/8672823/235594764-7038a89f-5ecc-4d31-a2dd-7cd51d55f80b.png)

**Versions:**

* OS: mac
* Studio Version 14.0.2

**Additional context**
Any suggestions?

**Comment by kneth** [comment]
The error message could indicate that your file is read-only.

**Comment by robertnicjoo** [comment]
> The error message could indicate that your file is read-only.

I don’t think that’s the issue. I just installed version 11.2.0 which is the version my file was last edited with and it’s opening without issue but on this latest version it doesn’t.

**Comment by ankitk-nimblechapps** [comment]
Yes getting the same error, in the latest updated version too, my current realm studio version is 14.0.2

![Screenshot 2023-05-04 at 2 51 38 PM](https://user-images.githubusercontent.com/77725221/236163457-7b499767-0d06-464f-bb11-7fc399d13bb3.png)

**Comment by kneth** [comment]
@ankitk-nimblechapps @robertnicjoo We have a fix in https://github.com/realm/realm-studio/pull/1579

**Comment by robertnicjoo** [comment]
It is not merged yet to test it

**Comment by yoontaeseong** [comment]
The same thing happens on my laptop too.

Versions:

OS: mac / m2
Studio Version 14.0.2

**Screenshots**
<img width="896" alt="스크린샷 2023-05-10 오전 11 51 00" src="https://github.com/realm/realm-studio/assets/79886121/4793a9b8-4bec-4192-a7db-b9c8bc5eae97">

**Comment by kneth** [comment]
The fix has been released in v14.0.3
