### ISSUE TITLE
Missing Tooling

### ISSUE THREAD

**Issue by Morons** [realm/realm-studio#1586]
1. I'd like to be able to Import Json {Bson} data as exported from Compass instead of CSV
2. I'd Like to have "New" Realm function to create a schema, then export it to my language of choice

The reason for 1. is that when using MongoDb (Not Nessesary Atlas) on my own Kotlin/Ktor written API back-end I need to match the schemas with that data.!

**Comment by kneth** [comment]
@Morons Thank you for your two proposals. 

Importing JSON/BSON can a bit complicated, and I would like to understand your proposal. For example, do you wish Studio to derive the schema from the data or has the schema been created prior to importing? And in the latter case, should the entire import fail if a single object cannot be validated against the schema?

I believe Studio does support Kotlin, so can you explain what additional functionality you need?

**Comment by kneth** [comment]
I am closing the issue due to no reply back. Please create a new issue if you have new observations to share.
