### ISSUE TITLE
History type not consistent

### ISSUE THREAD

**Issue by AgnelSelvan** [realm/realm-studio#1589]
**Describe the bug**
Working on a Flutter Desktop based App and using realm as a database in our app. When tried to open the **default.realm** file in realm-studio facing **History type not consistent** issue and the data is not displayed in the realm-studio app. 

**To Reproduce**

1. Create a new Flutter project and import **realm** in your _pubspec.yaml_ file
1. Do some CRUD operation
1. Now open the deafult.realm file in realm-studio app you will be getting this issue.

**Screenshots**
![](https://github.com/realm/realm-studio/assets/47639176/aa572bdf-10d4-44e2-b1a4-3dd36439b460)

**Versions:**

* OS: MacOS Monterey version 12.6.8
* Studio Version 14.0.3 (14.0.3.22)

**Comment by kneth** [comment]
@AgnelSelvan Thank you for reporting. A simple follow-up question: between 2. and 3., do you close the Flutter app? If not, try to do that as I believe we don't support multiprocess access of synced Realms.

**Comment by AgnelSelvan** [comment]
Yeah, it worked after closing the app and opened it, it worked. Thanks @kneth.
