### ISSUE TITLE
Database has an unsupported version (24) and cannot be upgraded

### ISSUE THREAD

**Issue by victorcode1** [realm/realm-studio#1636]
![Captura de pantalla 2024-03-22 a la(s) 10 19 05 a  m](https://github.com/realm/realm-studio/assets/55858068/51ef0095-6c53-4209-84dd-7273a32c77f2)
Database has an unsupported version (24) and cannot be upgraded

 - Studio Version [14.1.2]

**Comment by kraenhansen** [comment]
Thanks for reporting this, we'll make sure to get a new release out soon.
What SDK (and version) did you use to produce this database file?

**Comment by andgordio** [comment]
I had the same issue. In my case, I didn't notice that the dependency rule in SPM was set to branch/master when I was adding the package. I resolved the problem by deleting the realm file and re-installing the package with the Up to next major setting.

**Comment by knog99999** [comment]
@kraenhansen Hi, I'm experiencing the same issue and used Flutter realm2.0.0. Thank you

**Comment by kraenhansen** [comment]
@victorcode1, @andgordio and @knog99999 [Realm Studio v15.0.0](https://github.com/realm/realm-studio/releases/tag/v15.0.0) was just released with support for file format v24.

**Comment by victorcode1** [comment]
Tnk @kraenhansen
