### ISSUE TITLE
Use the new sass library instead of node-sass

### ISSUE THREAD

**Issue by gagik** [realm/realm-studio#1652]
**Is your feature request related to a problem? Please describe.**
CI seems to have updated to python `3.12` by default. `node-sass` is [deprecated](https://github.com/sass/node-sass/?tab=readme-ov-file#node-sass) and was breaking CI lint because one of its dependencies was using a python standard library which was removed in 3.12: https://github.com/nodejs/node-gyp/issues/2869. Right now the issue is "fixed" by setting our Python version to `3.11` but it'd be good to have latest `sass` installed which removes the need for this.

`sass` will also help us ensure better compatibility with the `arm64` runner.

**Describe the solution you'd like**

1. Remove `node-sass`.
2. Remove the `Setup Python 3.11` from the linting GitHub Actions workflow.
3. Add `sass` as a dependency. 
4. Fix `sass` warnings we have in our repository (mainly related to deprecated SASS properties).

**Describe alternatives you've considered**
We can also just continue using `node-sass` and `Python 3.11` or wait for a potential update of the library.

**Additional context**
See https://github.com/realm/realm-studio/pull/1651

**Comment by kraenhansen** [comment]
As discussed elsewhere, this is probably caused by https://github.com/sass/node-sass/issues/3033 since the `macos-latest` runner on GHA is now arm64.
