### ISSUE TITLE
Can't open device sync in realm studio?

### ISSUE THREAD

**Issue by Alex25197** [realm/realm-studio#1665]
Hello,

I'm having a weird case, recently downloaded realm studio 15.20.0 it installed correctly but when I tried to connect into my appID, it throws me this error always:
<img width="304" alt="image" src="https://github.com/realm/realm-studio/assets/23437061/e3f5ede9-2e95-4e8a-8970-183c15c59228">

The thing is, that I tried with many differents appIds all with the same outcome: Realm.App._clearAppCache is not a function
I don't know if this is specific because I'm using an M1 Mac?

Thanks in advance

**Comment by kraenhansen** [comment]
Thanks a lot for reporting this - a fix is released in Realm Studio v15.2.1.
Please allow the app to auto-upgrade and report back if you're still experiencing any issues.

**Comment by Alex25197** [comment]
Hello, thanks for the fast response, and indeed it works now, but I got another error.

When I open the realm it shows empty but I have some classes already that I created from atlasdb, and when I try to create a new class it shows me this:

<img width="888" alt="image" src="https://github.com/realm/realm-studio/assets/23437061/ea9ffbcf-fa0a-4a05-99ac-86e8b07b8f47">

And after that it shows me this:
<img width="901" alt="image" src="https://github.com/realm/realm-studio/assets/23437061/5ffc6656-876c-4cfd-b8db-8a3acc0b8ab1">

Let me know if I need to open another ticket for this case since it goes out of the scope of the original one and thank you again for the fast response!

**Comment by kraenhansen** [comment]
> open another ticket for this case

Yes please. I tried (but failed) to reproduce neither of the two errors myself and we would need a bit more help with steps to reproduce it. Does the database contain much data server-side? Can you try clicking "Clear Cache" from the "Help" dropdown in the top menu and try again?
