### ISSUE TITLE
Impossible to find out a user's id

### ISSUE THREAD

**Issue by icanzilb** [realm/realm-studio#394]
It is impossible to find out a user's id when seeing the user list in Studio.

![image](https://user-images.githubusercontent.com/633862/32678604-5440d104-c663-11e7-955a-e4d612d366cc.png)

The problem being that the ID is cut-off everywhere so I can never see and copy the full string

Realm Studio: Version 1.7.2 (1.7.2.147)

**Comment by roberhofer** [comment]
@kraenhansen : did you find a solution in the meantime? :-) e.g. can this be closed?

**Comment by kraenhansen** [comment]
Yep - I believe we show the entire ID, wrapping it across multiple lines.
