### ISSUE TITLE
Studio v1.7.3: Opening large realms ( > 1MM records) takes exceeding long time to fully load 

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-studio#419]
Getting a large realm to fully load on open seems to never complete.  This is best demonstrated by example -  try to open the realm object server at: 165.227.108.150 (username/password are the default) and open the `/RealmEdgeCache` realm

It ill take several minutes event to get to an initial display of the rows; but then will seemingly never completely load... 

SSH keys for @bigfish24, @kraenhansen and others are installed should you want to log into this machine directly to examine the setup.

The server lives in /root/udndemo2-data/DemoServer

**Comment by ianpward** [comment]
@roberhofer Assigning to you for server-side product backlog - this is what we need pagination support for

**Comment by kraenhansen** [comment]
@ianpward as there are multiple ways of solving this issue, I think it would be better to focus on this concrete suggestion: https://github.com/realm/realm-studio/issues/780 and close this issue once 780 is fixed.

**Comment by ianpward** [comment]
Sure - Agreed

**Comment by bmunkholm** [comment]
As we have #780 and are progressing on that, seems like there is no need to keep this issue.
