### ISSUE TITLE
When upgrading Studio it doesn't restart

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#526]
![image](https://user-images.githubusercontent.com/1215687/33725353-bf096a8c-db26-11e7-9a77-2a9b39fcbeee.png)

No way to use the new version?

When I restart Studio, it downloads version 10 again. And this time with the popup appearing (on another screen than Studio is. Hidden behind a browser window. Was only visible because the Icon in the Dock was flashing.

**Comment by kraenhansen** [comment]
I consider this a duplicate of https://github.com/realm/realm-studio/issues/1129
