### ISSUE TITLE
No info given when CSV import fails.

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#535]
https://github.com/realm/realm-core/tree/master/test/csv_test
has a lot of CSV files. When importing some of them, nothing happens and no information is given about any failures. try e.g. https://github.com/realm/realm-core/blob/master/test/csv_test/vend_products_31Aug12.csv

**Comment by kraenhansen** [comment]
I believe this was fixed, please retry with v10.1.2 and v5.0.3 and reopen if the issue persists.

**Comment by kathychoi2019** [comment]
동글동글 징그러운 소리

2021년 2월 18일 (목) 오후 5:08, Kræn Hansen ***@***.***>님이 작성:
