### ISSUE TITLE
On-boarding issues with cloud.12

### ISSUE THREAD

**Issue by bigfish24** [realm/realm-studio#545]
In the current Realm Studio cloud tutorial there are two issues:

1. The code for index.js assumes port 80 using http and realm instead of https and realms
2. The default password for realm-admin is unknown to me when creating the cloud instance in Studio
3. The code has a primary key for tickerSymbol which leads to this in Studio (seem unnecessary since the first thing I did was to edit that property to see sync work):

![image](https://user-images.githubusercontent.com/1036685/34002859-9de45952-e0a8-11e7-8759-90e52f52ff7d.png)

It would be nice for Studio to just put the URL in any code snippet for you

**Comment by kraenhansen** [comment]
Closing this as Realm Studio only links to tutorials since https://github.com/realm/realm-studio/pull/884 got merged.
