### ISSUE TITLE
Tutorial: NPM step

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#550]
Not everyone has NPM installed on their machine. We should probably link to some guide(s) somewhere that describes how to install it if needed.

![image](https://user-images.githubusercontent.com/406066/34004564-88417a58-e0f8-11e7-9919-8d2d3b07fe54.png)

**Comment by kraenhansen** [comment]
Closing this as Realm Studio only links to tutorials since https://github.com/realm/realm-studio/pull/884 got merged.
