### ISSUE TITLE
Tutorial: Run the script

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#553]
Tested with `cloud.12`

When following the guide to run the sample script, this is the output on my screen:

I just copied the URL that Studio showed me in the upper right corner: `https://cmelchior.us1.cloud.realm.io`. Trying to use `http://cmelchior.us1.cloud.realm.io` instead did not fix it.

```
 => node index.js
(node:57911) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): FetchError: request to http://https://cmelchior.us1.cloud.realm.io/auth failed, reason: getaddrinfo ENOTFOUND https https:80
(node:57911) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Having errors being outputted as the first thing when starting ROS feels very offputting. I'm not sure if this is an error in the Studio Guide or something in ROS, but we should make sure these errors do not happen.

**Comment by kraenhansen** [comment]
Closing this as Realm Studio only links to tutorials since https://github.com/realm/realm-studio/pull/884 got merged.
