### ISSUE TITLE
Minor: Resizing columns smaller than the column type could use some fine tuning

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#589]
Before resize:
![image](https://user-images.githubusercontent.com/1215687/34423881-97608b5a-ec1f-11e7-81a8-855600010b1e.png)

After resize:
![image](https://user-images.githubusercontent.com/1215687/34423903-c9d4e64e-ec1f-11e7-8a70-6c3b74882bfd.png)

Also some funny behavior happens with the name when resizing very small. Name changes to "...", then to the first letter. Also the Header column stops resizing before the content columns. 

It's a minor thing in the big picture, so prioritize low.

**Comment by kraenhansen** [comment]
I believe this was fixed with https://github.com/realm/realm-studio/pull/941.
