### ISSUE TITLE
Users wants a list of recent databases & servers

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#632]
Based on the comment from https://github.com/realm/realm-studio/issues/17#issuecomment-322527085 we want users to see a list of their most recently opened:
- Local Realm database files
- Remote (synced) Realm databases
- Realm Object Servers

This should probably be displayed in the right sidebar of the GreetingWindow.

Perhaps it could make sense to use the OS level API to store recently opened files: https://github.com/electron/electron/blob/master/docs/api/app.md#appaddrecentdocumentpath-macos-windows

**Comment by astigsen** [comment]
duplicate of #105?

**Comment by kraenhansen** [comment]
Yeah - it looks like it.
