### ISSUE TITLE
Show object level permissions in Studio

### ISSUE THREAD

**Issue by astigsen** [realm/realm-studio#683]
When browsing Realms, you should be able to see (and edit) the permissions on the individual objects. 

The UI could be similar to how we can currently see Realm-level permissions (a sidebar that shows up when you select a row).

This will help users understand the permission model, and will also help our own testing and debugging as we build out the object-level permission feature.

**Comment by roberhofer** [comment]
@kraenhansen : is there actually a API that is available to you to expose this in Studio?

**Comment by kraenhansen** [comment]
The permissions are determined by the __* classes available in the Realm when opened in the query-based mode, so yes - I think I have the API available to expose this in Studio.

**Comment by bmunkholm** [comment]
@kraenhansen What's current estimate on the amount of work left on this?

**Comment by kraenhansen** [comment]
For individual objects specifically, I expect to have something ready for review end of day Wednesday and I expect to have a more polished feature end of week.

**Comment by kraenhansen** [comment]
For the interested I've created an "in active progress" PR with screenshots of the current state of this feature: https://github.com/realm/realm-studio/pull/946.

**Comment by roberhofer** [comment]
Very Cool. @ianpward : have a look please at https://github.com/realm/realm-studio/pull/946
