### ISSUE TITLE
Cannot log into Studio 1.18.4

### ISSUE THREAD

**Issue by mbalex99** [realm/realm-studio#697]
I pressed "Connect to Realm Cloud" and even tried the retry button.

Version: 1.18.4

![image](https://user-images.githubusercontent.com/2183729/36317910-35bd5888-12f3-11e8-827e-0b6e1f305720.png)

**Comment by astigsen** [comment]
Closing this for now as it relates to an outdated version of Studio. Please reopen if the problem resurfaces.
