### ISSUE TITLE
Failed while contacting Realm Cloud Open Realm file Connect to Server v1.18.4

### ISSUE THREAD

**Issue by mbalex99** [realm/realm-studio#698]
1. I closed and opened several times. 
2. Deleted local data directory 
3. Closed and Opened several times.

Only happened within the last hour:

![image](https://user-images.githubusercontent.com/2183729/36328153-efdcedce-1315-11e8-96ac-071972d358d5.png)

**Comment by astigsen** [comment]
Closing this for now as it refers to an outdated version of Studio. Please reopen if the problem resurfaces.
