### ISSUE TITLE
Stuck at "Fetching your profile and instances"

### ISSUE THREAD

**Issue by jedelbo** [realm/realm-studio#725]
1. Start Realm Studio.
2. Log in to Realm Cloud
3. After logging in, it just stays in the "Fetching your profile and instances" state forever.

If you then close Realm Studio and open it again, then it logs in immediately and displays the "Connect to Realm Cloud" option.

**Comment by 386sx** [comment]
Anything new on that? I'm trying to build a first project and stuck here.
