### ISSUE TITLE
Node.js tutorial details

### ISSUE THREAD

**Issue by jedelbo** [realm/realm-studio#726]
The tutorial works well. Only a few details:

Step 6: The example picture should probably be taken from a Realm Cloud instance
Step 6: You should probably be told that you will have to stop the application by pressing <ctrl> c
Step 7: You will have to double-click OR click and then "Open"

**Comment by kraenhansen** [comment]
Closing this as Realm Studio only links to tutorials since https://github.com/realm/realm-studio/pull/884 got merged.
