### ISSUE TITLE
Add permission window doesn't show username in pick list, only SyncUser.identifier value

### ISSUE THREAD

**Issue by dhmspector** [realm/realm-studio#728]
Trying to create a new wildcard permission - the resulting dialog shows only the SyncUser.identity value for non-admin users and not the username  (see image below).  

I think this is a regression - I distinctly remember the username being visible in this window/dialog previously. 
![studio-missing-username-permsdialog](https://user-images.githubusercontent.com/21057/37057823-787d00da-213d-11e8-9452-bdb5c0fd1b8a.png)

**Comment by astigsen** [comment]
Closing this for now as there has not been any update from user for months. Please reopen if the problem resurfaces.
