### ISSUE TITLE
Confusion popup action

### ISSUE THREAD

**Issue by jedelbo** [realm/realm-studio#747]
If you have an object with a link to another table and you right-click the link field, you will get a popup like this:

![realm studio screenshot](https://user-images.githubusercontent.com/572755/37285724-2f342f58-2600-11e8-918f-1af7ffb6be36.png)

I think the "Delete" option should be rephrased as "Delete row" or similar. Otherwise you might select this option if you just want to delete the link.

**Comment by kraenhansen** [comment]
This was solved when #593 was merged - now its "Delete object" or "Delete objects"
