### ISSUE TITLE
Unable to create a permission using the UI

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-studio#767]
It looks like when having multiple windows, clicking on `Create new __permission` which should display a new window/popup is not shown 

here's an example
![unable_to_create_permission](https://user-images.githubusercontent.com/1793238/38311820-fed2caa2-3817-11e8-9076-ec6b3d840fe7.gif)

same when trying to create a `__Role`
![unable_to_create_role](https://user-images.githubusercontent.com/1793238/38312493-d6dbecfc-3819-11e8-83c6-3b2e7e25de7b.gif)

Test on `1.19.1` (since I still need to open partial sync)

**Comment by astigsen** [comment]
@kraenhansen @nhachicha is this still valid?

**Comment by nhachicha** [comment]
Well, the `Create new __Permission/__Role` buttons on top, have disappeared in the latest version ... I'm not sure if this was a redesign or removed because of this bug?

**Comment by kraenhansen** [comment]
I believe I addressed this with https://github.com/realm/realm-studio/pull/832
