### ISSUE TITLE
Blank Realm window after first partial sync connection 

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-studio#768]
- Start with a new ROS instance
- Open the default Realm window
- Use a client to upload a schema to `default` using partial sync (_I doubt it's partial sync related I assume the same problem will exist with a global Realm_).
- Now the window will turn blank, we need to close it & re-open the `default` Realm in order to see the updated schema

![blank_window_after_first_partialsync](https://user-images.githubusercontent.com/1793238/38313223-7f71e28a-381b-11e8-9546-a27d91c78a39.gif)

**Comment by astigsen** [comment]
Closing this for now as it refers to an old version of Studio. Please reopen if it resurfaces in the latest version.
