### ISSUE TITLE
Logging into Cloud hangs on Ubuntu

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#771]
Discovered this during a user test. He was using Ubuntu.

If you open Realm Studio without having given Realm Studio sufficient privilieges, logging into Cloud just hangs and never completes. Exiting Realm Studio and giving priviliges fixes it.

I would assume the network layer would throw some kind of error in that case, or at least time out at some point (we left it running for 2-3 minutes). We should double check if we do time out or handle these kinds of errors in this case.

**Comment by astigsen** [comment]
Closing this for now as we have not seen in resurface. Please reopen if you see the issue again.
