### ISSUE TITLE
Users wants to browse a huge "reference" Realm in query-based mode

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#780]
To help reduce the pain of browsing large Realm files (https://github.com/realm/realm-studio/issues/419) a users needs a way to open Realms in a query-based mode where only a subset of data is initially synchronized and data is synchronized on demand, when the user is browsing the Realm.

The behaviour should essentially be the same as now - perhaps with some spinner indicating that the data associated with the query is being updated.

---

From a technical standpoint the prerequisites are:
1. the RealmFile has `realmType === 'reference'` and
2. we need to be able to create a query with a filtering and stable sorting and adjust the limits (from element 0 to `x` where `x` is increased as the user scrolls through the objects)
3. we need to be able to tell when the collection of objects associated with a query can be considered up-to-date (as we want to show the user if we are synchronizing or they can trust the view of the data as-is).

**Comment by ianpward** [comment]
@kraenhansen this has been shipped in sync - the Swift API looks as follows:
````
syncSubscription = realm.objects(objectType).filter(queryString).subscribe(limit: limit)

```

**Comment by kraenhansen** [comment]
@kneth do we have something similar to @ianpward's comment in Realm JS? I see the method to subscribe only takes a name: https://realm.io/docs/javascript/latest/api/Realm.Collection.html#subscribe

**Comment by nirinchev** [comment]
You can specify a limit in the string query itself.

**Comment by kneth** [comment]
@kraenhansen See https://realm.io/docs/javascript/latest/api/tutorial-query-language.html section "Limiting the size of the result set"

**Comment by bmunkholm** [comment]
@kraenhansen Can you please writeup what is missing to complete this now?

**Comment by kraenhansen** [comment]
The current state of implementation is on https://github.com/realm/realm-studio/tree/kh/realm-browser-with-context, which is mostly refactoring the browser to use the [react-realm-context](https://www.npmjs.com/package/react-realm-context) library in favor of the highly coupled (and very inflexible) [RealmLoadingComponent](https://github.com/realm/realm-studio/blob/master/src/ui/reusable/RealmLoadingComponent/index.tsx) - AFAIR that part is almost done.

Missing is:
- [ ] Hooking into the [onClassFocussed](https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/index.tsx#L447-L453) or the `RealmBrowsers` [componentDidUpdate](https://reactjs.org/docs/react-component.html#componentdidupdate) method to create limited named subscriptions matching the new focus
- [ ] Optionally cleaning up the subscriptions that the user is no longer focussing.
- [ ] Listen change in scroll passed as [property to the Table](https://github.com/realm/realm-studio/blob/master/src/ui/RealmBrowser/Content/Table/index.tsx#L123) and update the limit of the named subscription to load new data as the user scrolls.
- [ ] Show placeholders for loading rows.

While doing the above - we should ensure that the browser still works with full-synced and local Realms and does not get too bloated with abstractions.
