### ISSUE TITLE
Remove the build-in tutorials

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-studio#781]
I gathered here some issues I observed, they're all related to the tutorial so I grouped them in the same issue:

- [ ] Step 6
> ... login to your ROS running **locally** via the **default admin** ...
 
It's not local, since this is the demo for cloud, plus we don't use the defaul admin (we created a regular user on the previous step 6).

- [ ] Step 6 & 7 
Remove/update reference to the global Relam `/tickers`

It's not a reference Realm, the code creates a user Realm. Update the URL to reflect this (it's created under `/8c569caabad655544e80441dd9ccc324/tickers` for example).

The screenshot is also wrong (shows the local/reference Realm) 

- [ ] Step 7 
> Congrats you have successfully synced your first data with Realm Object Server **2.0!**

The version is irrelevant for the user (let alone being incorrect) plus he/she is running the cloud, so no idea about the ROS version, also probably update "Realm Object Server" to "Realm Object Cloud"

**Comment by mgeerling** [comment]
@kraenhansen @astigsen -- the embedded tutorial is out of date and hard to maintain.  Can we just get it removed in favor of linking to our documentation?  I've effectively rewritten for use with partial sync / reference realm within our getting started

**Comment by kraenhansen** [comment]
I agree - this was added very fast at a point in time where we didn't know where / how we wanted the tutorial UX to be.

**Comment by astigsen** [comment]
Yes, let's remove it and focus our efforts on the web based tutorials.

**Comment by mgeerling** [comment]
how quickly can we get this done?  Seems like pretty low effort for something that essentially every user sees (especially cloud users)

[Here is link](https://docs.realm.io/platform/getting-started-1#learn-how-to-pre-populate-data-with-our-server-sdks)

**Comment by kraenhansen** [comment]
I agree - this is a small task.

**Comment by kraenhansen** [comment]
https://github.com/realm/realm-studio/pull/884 removes it entirely, if we want a link to the tutorial - where what should the text for that be? I suppose we could also add this to the "Getting started" scene on Realm Cloud.
