### ISSUE TITLE
Remove setFeatureToken from Node.js tutorial (code)

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-studio#782]
The tutorial for Node JS is still using the feature token, which was deprecated since the user is using the tutorial for the cloud, it makes sense to remove it
```Javascript
const token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJSZWFsbSIsIk5vdGlmaWVyIjp0cnVlLCJTeW5jIjp0cnVlLCJpYXQiOjE1MTI2NTY3Nzh9.iKhiNXtCT5HtEZc0SKlNnZOaCU8XSpbVYCyGm6RKgw3_tQogN5Ln5oG7bfFTBNJKi0zbjKVJcFGtBhxus27BWYgdVUTH_AHswfEY4BuaRKWK1dvUPn1mx7Fp7lQHnCPwp_nvhaqDAu5h7k3w2qIrbZfojAFhOHip_TbYHN4sI_EE7xO97IXv3Ya7bbKUZnuI_W1qWrQHw3pGH8TNyRTDaqS-xk7ko-S7iNm4HLTrt9562gbMItB_yHC2_7w7jOqd8ZRxPhpehEb6sWbQxyOFzOreClmC1JB_9mYlFmb1QsgqhY-VIKvdpUca98h_0zsEcyaVqGYalpbqb6Un7vAQ6w";

// Unlock Professional Edition APIs
Realm.Sync.setFeatureToken(token);

```

**Comment by astigsen** [comment]
Closing this for now as I can not find any reference to feature token in any of our current tutorials. Please reopen if you discover places where it is still present.

**Comment by astigsen** [comment]
Actually, I missed that this was referring to the tutorial in Studio. The token is still referenced there. We should fix that.

**Comment by kraenhansen** [comment]
Closing this as Realm Studio only links to tutorials since https://github.com/realm/realm-studio/pull/884 got merged.
