### ISSUE TITLE
deleting multiple objects fails

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#788]
From https://forum.realm.io/t/i-can-not-delete-a-lot-of-objects-in-realm-studio/1329

I could delete about 10 objects from my classes list in Realm Studio by right click “Delete selected objects” after selecting objects.

But I could not delete about 30 objects by same way.

Realm Studio displayed this error message.

Error deleting the object:
object must be of type ‘object’, got (undefined)

Realm Studio Version is “1.21.0 (1.21.0.267)”.

My problem resolved by repeating delete.

**Comment by kraenhansen** [comment]
Okay - this is the topmost issue on a list of issues that @davidhratner set to me in a PM on Slack that I understand and can make progress on. Therefore I am starting to fix it.

I can indeed reproduce this issue now - and it's twofold:
1. An error appears if you are deleting more than half of the objects in a Realm
2. When deleting an object the neither the filtering nor the sorting is not respected.
