### ISSUE TITLE
Import multiple CSVs at once

### ISSUE THREAD

**Issue by ianpward** [realm/realm-studio#790]
https://forums.realm.io/t/is-it-possible-to-specify-a-field-type-for-csv-import-in-realm-studio/981

**Comment by kraenhansen** [comment]
I believe this was already fixed - the user just needs to select multiple files in the open files dialog, perhaps the docs should mention this ability?

The only outstanding as per the forum thread is "specify the field type of the objects" I've created on a separate issue: https://github.com/realm/realm-studio/issues/826.

Therefore I am closing this issue.
