### ISSUE TITLE
Windows: Support long file paths

### ISSUE THREAD

**Issue by ianpward** [realm/realm-studio#793]
See discussion here:
https://realmio.slack.com/archives/CA3ET33NU/p1527116304000354

**Comment by roberhofer** [comment]
This is a nice example for the engineering backlog that Kraen should be able to pick up as he sees fit. 
(E.g. a pebble vs. product big rocks).

**Comment by kraenhansen** [comment]
Looking into this I can actually reproduce the error on MacOS as well - so it does not seem to be a window only issue:

If I connect to a server via Studio on MacOS and try to create a realm with this 260 char long path:
```
tonyixhjaaavggucolzihusbnibdswrtkhvfflhzedizmrxkhpbwmcsfwbcutawnkomwfouhjqevtyedzghhgxyqqqzdfnbchlcwcsnogpmjqmddgxrjbrmjuwvujpoyeyugnoppoqqejwhqgogoshkkzezjayfhuicyhscqrwskhzflhoviigybwopldifhjvdwvxfudnxnikxpdapvwefuyddkjchksxlqbksnfnolaextqvhxindlcwrfjrqjezqi
```

It get this error thrown:

```
Failed to create Realm:
Unable to open a realm at path '/Users/kraenhansen/Library/Application Support/Realm Studio/renderer-73853/realm-object-server/6347a228-8ec3-4a2f-8c66-b54b83ca8dd3/realms%3A%2F%2Fgorgeous-rubber-hat.us1a.cloud.realm.io%2Ftonyixhjaaavggucolzihusbnibdswrtkhvfflhzedizmrxkhpbwmcsfwbcutawnkomwfouhjqevtyedzghhgxyqqqzdfnbchlcwcsnogpmjqmddgxrjbrmjuwvujpoyeyugnoppoqqejwhqgogoshkkzezjayfhuicyhscqrwskhzflhoviigybwopldifhjvdwvxfudnxnikxpdapvwefuyddkjchksxlqbksnfnolaextqvhxindlcwrfjrqjezqi.management': make_dir() failed: File name too long.
```

**Comment by kraenhansen** [comment]
I created https://github.com/realm/realm-object-store/issues/686 to track a suggestion to have the client store realms at a shorter path.
