### ISSUE TITLE
Tickbox of "Save credentials" has no margin

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#817]
![image](https://user-images.githubusercontent.com/1215687/41099845-074d52e0-6a60-11e8-99ac-d1447c8444ba.png)

**Comment by SogoGolf** [comment]
hi, i submitted a pull request yesterday that fixes this

**Comment by cmelchior** [comment]
Hi @SogoGolf 
It doesn't look like from this list https://github.com/realm/realm-studio/pulls ?
