### ISSUE TITLE
Update Realm Cloud staging and testing URLs

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#828]
After [a Realm Cloud](https://github.com/realm/raas/pull/1098) PR got merged we have new staging and testing environments and Studio should update its GitHub client IDs for these.

**Comment by alebsack** [comment]
@kraenhansen You need the testing GitHub client ID as well?  I wonder if we can make this a configurable option in studio?

**Comment by kraenhansen** [comment]
@alebsack as in from an end-users perspective configurable? Currently they are defined here as an enum https://github.com/realm/realm-studio/blob/master/src/services/raas/index.ts#L29-L32.

Regarding Github client ID - I don't think so. We are currently using a single shared ID https://github.com/realm/realm-studio/blob/master/src/services/github/index.ts#L34.
