### ISSUE TITLE
Linux: Server administration window crashes

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#841]
**Describe the bug**

I see this in the main process when running Realm Studio 2.2.0:

```
/tmp/.mount_instal7w6CmU/app/realm-stu: symbol lookup error: /tmp/.org.chromium.Chromium.t4Fezq: undefined symbol: SSL_get0_param
```

**To Reproduce**

See the instructions on https://github.com/realm/realm-js/issues/1864.

**Expected behavior**
No crash.

**Screenshots**

<img width="1052" alt="skaermbillede 2018-06-15 kl 18 07 31" src="https://user-images.githubusercontent.com/1243959/41478171-041575ea-70c7-11e8-95c7-ed1c09030d8b.png">

**Versions:**
 - OS: Linux / Ubuntu 16.04
 - Studio Version 2.2.0

**Additional context**

See https://github.com/realm/realm-js/issues/1864

**Comment by kneth** [comment]
Ugly work-around (on Ubuntu 18.04):

```
sudo apt install libssl1.0
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 ./installer-2.3.2.AppImage
```

**Comment by kraenhansen** [comment]
@kneth seems to have unblocked this with https://github.com/realm/realm-js/pull/1912. Looking forward to an upcoming release of Realm JS :)

**Comment by kraenhansen** [comment]
Unfortunately this wasn't fixed.

**Comment by kraenhansen** [comment]
This was fixed now with https://github.com/realm/realm-js/issues/1864 (see https://realmio.slack.com/archives/CA3ET33NU/p1530919260000141 too).
