### ISSUE TITLE
Select and delete multiple Realms

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#846]
I want to be able to select multiple Realms and delete them all in go. This is especially useful when testing query-based Realms which can create a large number of Realms. In that case it would be useful to be able to select them all and delete them in one go.

Right now I have to manually select and delete every one of them

![image](https://user-images.githubusercontent.com/406066/41527478-94653776-72e7-11e8-9046-aaa244688a2e.png)

**Comment by kraenhansen** [comment]
I've created an issue in ROS to track a change I would like to have happen before implementing this: https://github.com/realm/realm-object-server-private/issues/1149

**Comment by kraenhansen** [comment]
For now, I'll just be spamming the HTTP endpoint.
