### ISSUE TITLE
Allow select multiples rows in 'Add existing ...' dialog 

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-studio#859]
**Is your feature request related to a problem? Please describe.**
I need to add hundreds of items into the list of another object. The 'Add existing...' dialog does not seem to support multiple selection using Shift-click or Shift-drag. It is very frustrating (and error prone) to have to add these one-by-one.

**Describe the solution you'd like**
Support Shift-click, Shift-drag (and Select All) in the 'Add existing...' dialog

**Describe alternatives you've considered**
Laboriously adding items one-by-one to a list.

**Comment by SogoGolf** [comment]
I'd love to see this too

**Comment by kraenhansen** [comment]
I'll be releasing a fix for this soon.

**Comment by DanielAsher** [comment]
@kraenhansen Thanks!

**Comment by kraenhansen** [comment]
@DanielAsher This got released as Realm Studio 2.4.0 - please verify that this works as expected or reopen this issue.
