### ISSUE TITLE
As a developer I can use Studio to see the size of each realm on the server

### ISSUE THREAD

**Issue by roberhofer** [realm/realm-studio#862]
See as well tickets: 

\* [1080](https://github.com/realm/realm-object-server-private/issues/1080)

\*  [812](https://github.com/realm/realm-studio/issues/812)

Created from Aha! https://realmio.aha.io/features/ROS-31

**Comment by roberhofer** [comment]
...

**Comment by kraenhansen** [comment]
Duplicate of https://github.com/realm/realm-studio-private/issues/2.
