### ISSUE TITLE
Realm Studio 1.21 - screen goes blank after deleting collections or realms

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#864]
@SogoGolf commented on [Sat May 19 2018](https://github.com/realm/realm-object-server/issues/376)

- installed on Mac OSX 10.13.4

- deleted a Realm. saw this (see screenshot). tried a few times, same result for any/all Realms.

![2018-05-19_18-39-39](https://user-images.githubusercontent.com/19580787/40266775-5dd352e8-5b94-11e8-805c-56a1a10c1b89.png)

---

@guatedude2 commented on [Sat May 26 2018](https://github.com/realm/realm-object-server/issues/376#issuecomment-392231426)

I too have the same issue

---

@ElMoribond commented on [Sun May 27 2018](https://github.com/realm/realm-object-server/issues/376#issuecomment-392308697)

Same for me on Windows 10.
It's impossible to use it, I downgrade to 1.20.

In this regard, is there a possibility to disable the update check at startup ?

**Comment by bmunkholm** [comment]
Moved the issue to the now open source Realm Studio

**Comment by kraenhansen** [comment]
I believe this was fixed in the 2.3.3 release of Studio. Please reopen if that is not the case.
