### ISSUE TITLE
Not working with http proxy

### ISSUE THREAD

**Issue by letroll** [realm/realm-studio#866]
**Describe the bug**
Realm studio won't start with my company's http proxy because sentry.io is blocked I think 

`raven@2.6.2 alert: failed to send exception to sentry: Connection timed out on request to sentry.io
`

**Expected behavior**
Realm Studio Use http proxy rules from Internet explorer

**Versions:**
 - OS:Windows 7
 - Studio Version 2.3.3

**Comment by kraenhansen** [comment]
I think you might be right in the Sentry request being blocked, but I think the reason Studio does not work on your machine is that Realm JS does not run on Windows 7 and therefore Studio cannot run their either (see https://github.com/realm/realm-studio/issues/463). Please reopen if the issue persists when Studio is opened from within your network on a windows machine with a newer version and keep your eyes out for an updated version of Realm Studio that runs on Windows 7 - that may also happen eventually.
