### ISSUE TITLE
Allow option (or default) to delete User __perm and owned realms when deleting User

### ISSUE THREAD

**Issue by DanielAsher** [realm/realm-studio#872]
**Is your feature request related to a problem? Please describe.**
When I delete a User, all related realms (including the system realms) are left on the server. Currently I have to look up all related realms and delete them manually. Then I select View -> show system realms and delete the __perm files. Otherwise my ROS is littered with unused realms.

**Describe the solution you'd like**
When deleting a User I'd like the option to delete __perm files and the user-owned realm at the same time. 

**Describe alternatives you've considered**
Manual deletion. #846 would make this much easier, but a check box to allow automation would ease management.

**Comment by nirinchev** [comment]
This has been resolved with newer ROS releases.
