### ISSUE TITLE
Can't access realm instance

### ISSUE THREAD

**Issue by ianpward** [realm/realm-studio#876]
Freshdesk Ticket ID: <a href='https://support.realm.io/helpdesk/tickets/1246' target='_blank'>1246</a> <br/> Freshdesk Ticket Agent: Unassigned<br/>Freshdesk Ticket Agent Email: Unavailable<br/>Ticket Priority: Low<br/>Freshdesk Ticket Description:<div dir="ltr">
<div>I just updates my realm studio to 2.4.1 and I am now not able to access my instance in realm studio. I have tried logging out and back into studio, closing, and reinstalling. When I hit connect, the object server pops up and authenticates. The loading dots then appear and never loads.</div>
</div> <br/>

**Comment by ericjordanmossman** [comment]
The user is using Mac. They report that they were able to access realms in the instance locally. I asked for a test username/password to try and access the instance but they didn't know any. What other troubleshooting can we do?

**Comment by nirinchev** [comment]
Are they able to see the instance metrics on the dashboard?

**Comment by kraenhansen** [comment]
Eric told me on Slack that this got resolved
