### ISSUE TITLE
Improve error message when "Delete Realm fails, Unexpected token < in JSON at position 0"

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-studio#877]
<img width="1027" alt="screen shot 2018-07-26 at 18 17 25" src="https://user-images.githubusercontent.com/1793238/43277555-4e65b9d0-9100-11e8-8c1f-c2981a697267.png">

Version 2.3.2 (2.3.2.280)

**Comment by kraenhansen** [comment]
Okay - when deleting the file the server responded with something that was not parsable as JSON, can you check if the server logged something interesting when deleting was called? I'll keep this issue open to ensure the error is more user friendly in case of a bad non-JSON response.

**Comment by kraenhansen** [comment]
Fixed by https://github.com/realm/realm-studio/pull/897
