### ISSUE TITLE
Realms not properly deleted when open in a separate studio window

### ISSUE THREAD

**Issue by mgeerling** [realm/realm-studio#882]
**Describe the bug**
If a realm is open in studio and then deleted from another window, the list window will report that the realm has been deleted but it will not actually be deleted as long as it is open in another panel 

**To Reproduce**
1. Open realm in a studio window 
2. Move realm window to background and go to list view of all realms 
3. Delete the realm from studio main window 
4. See that Realm has not actually been deleted (as other window has kept it alive)  

**Expected behavior**
Realm should be deleted from server 

**Additional context**
It is possible that server can even hit errors (like diverging history) at this point if client was also reset

This would also be fixed by: https://github.com/realm/realm-studio/issues/649

**Comment by kraenhansen** [comment]
I believe this is happening because Realm JS running in the renderer (window) process syncs back the realm to the server. A simple solution could be to have the main process keep track of which path each browser window is opening and close just the windows that opened the realm file being deleted.

**Comment by mgeerling** [comment]
no idea, I would need to retest

**Comment by kraenhansen** [comment]
I think it's still an issue, yes.

**Comment by kraenhansen** [comment]
I just retested and I cannot reproduce it, please try again @mgeerling and reopen if you can still trigger this.
