### ISSUE TITLE
New User Experience: Wrapping long table names

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-studio#89]
When opening a file with long table names, they do not handle being to long very well

![image](https://user-images.githubusercontent.com/406066/30378528-cc80d7c0-9893-11e7-912e-ba363301b4b0.png)

*Sometimes the count is too close to the name
*Sometimes it wraps to the next line.

Ideally, some consistent behaviour would be nice. 

* If we think that the visual impression is important (aka staying on one line) and that resizing that column is coming ( #84), then I would prefer if the name gets dotted out as `VeryLongNa... (1)`

* If not, make sure that the counter does not come to close to the text.

I would much prefer 1)

**Comment by pavankataria** [comment]
When can we have resizable content panes? I'm on Realm Studio version `2.3.1.279` and still having to read table names like this:
https://i.imgur.com/X3v47KB.png

**Comment by kraenhansen** [comment]
@pavankataria we're tracking that here: https://github.com/realm/realm-studio/issues/84.
Until that gets fixed I'll encourage everyone to use short and concise class names.

I am curious though - are there good reasons to prefixing classnames with text like "RealmGlobalTravel"?
