### ISSUE TITLE
Menu is still using Partial Sync

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-studio#892]
<img width="197" alt="screen shot 2018-08-14 at 17 01 58" src="https://user-images.githubusercontent.com/1793238/44103319-cc60beec-9fe3-11e8-8850-a084fc9130b8.png">

It should be changed to query based Realm

Version 2.4.1 (2.4.1.286)

**Comment by kraenhansen** [comment]
Well .. it's actually a "gray-zone", technically they still have the "partial" type in the admin Realm.

Perhaps we should change it to "Show partial Realms (for query-based sync)"?
