### ISSUE TITLE
Change working directory only if it's truly needed

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#893]
To increase performance of connecting to a server (see https://github.com/realm/realm-studio/issues/169) and avoid downloading Realms twice, we could maintain a list of all synchronized Realms that a window is planning on opening and change the directory of a window only if it's planning on opening a synced Realm that another window has already opened.

**Comment by nirinchev** [comment]
Fixed with https://github.com/realm/realm-studio/pull/970
