### ISSUE TITLE
Realm Studio does not trust SSL certificate of Realm Cloud on Linux

### ISSUE THREAD

**Issue by kraenhansen** [realm/realm-studio#898]
This was discovered on Ubuntu 16.04 with the latest version of Realm Studio (2.5.0).

![skaermbillede 2018-08-15 kl 14 32 03](https://user-images.githubusercontent.com/1243959/44148346-4a093de2-a098-11e8-8462-7f59ca5847be.png)

~Clicking "Reconnect, trusting the certificate" reloads the window but the same error is shown, endlessly.~ This was fixed with https://github.com/realm/realm-studio/pull/905 but the issue of not automatically trusting the Realm Cloud certificate persists.

**Comment by kraenhansen** [comment]
Users can now (once again) choose to trust the a certificate, but the issue remains that Studio does not automatically trust the Realm Cloud certificates of Realm Cloud.

**Comment by nirinchev** [comment]
Should be fixed with https://github.com/realm/realm-studio/pull/951.
