### ISSUE TITLE
Unable to open encrypted files

### ISSUE THREAD

**Issue by Janglinator** [realm/realm-studio#907]
**Describe the bug**
As of version 2.6.1 (I previously had 2.4.1), I can no longer open encrypted files.

**To Reproduce**
Double click a realm file.  The screen just whites out.

**Expected behavior**
I am prompted with a field to enter the encryptionKey

**Screenshots**
![image](https://user-images.githubusercontent.com/8138981/44345858-0f916980-a45a-11e8-8156-7593740926b2.png)
![image](https://user-images.githubusercontent.com/8138981/44345863-1324f080-a45a-11e8-89c2-48c5db98c48f.png)

**Versions:**
 - OS: Mac 10.13.5
 - Studio Version 2.6.1

**Additional context**

**Comment by kraenhansen** [comment]
I tried but cannot reproduce this issue, can I have you try copying the realm file from your simulator to your desktop? I don't know exactly how this filesystem is mounted, but I suspect that it might be interfering with the memory mapping Realm is doing.

Do you get the same experience when opening the realm file by clicking the "Open Realm file" on the Greeting window?
![skaermbillede 2018-08-22 kl 11 32 16](https://user-images.githubusercontent.com/1243959/44455793-33da7b00-a5ff-11e8-9a78-d06b5784820c.png)

Would it be possible for you to share the file and its encryption key with me?

**Comment by Janglinator** [comment]
Moving it to the desktop does solve the issue.  I'll share the file in a bit, I can't get it open myself!

**Comment by Janglinator** [comment]
The directories aren't mounted or linked in any way (that I know of), and a typical directory would look like:

/Users/jangles/Library/Developer/CoreSimulator/Devices/69FB2249-E718-426A-8265-C10C71E6FEBE/data/Containers/Data/Application/97CCED1E-B2DB-486E-BDFE-CD87AEE94377/Documents/default.realm

They can definitely get pretty lengthy, but I can open non-encrypted realms fine without moving them to the desktop.  This only occurs with encrypted files.

What's even stranger is that even after downgrading back to version 2.4.1, I still have the same issue.  So either a) I haven't opened an *encrypted* realm in while, and didn't notice this (most of my recent projects have been non-encrypted), or b) the latest version got me into a broken state (not sure if this is possible, just speculating)

**Comment by kraenhansen** [comment]
Please retest this with v2.7.0 of Realm Studio that just got released and share the exception ID here.

Also - thanks for your patience 👍

**Comment by kraenhansen** [comment]
@Janglinator any luck retesting this? I would love to make the changes to fix the issue, but I need the exception ID to get a stacktrace.

**Comment by Janglinator** [comment]
Sorry, been out on vacation the past week!

I updated to version 2.8.0.299, and still get a white screen.  I noticed in a commit, you intend to spit out a message on the UI, but I don't see that either.  Simply a blank window

**Comment by kraenhansen** [comment]
Okay - then the crash is not happening in the React component tree, I got your email and I'll be testing with the Realm you sent me. Thanks again for your patience.

**Comment by Janglinator** [comment]
No prob!  Sorry for the slow response.  Feel free to email back, I check that much more frequently.

**Comment by kraenhansen** [comment]
@Janglinator I just sent you an email.

**Comment by kraenhansen** [comment]
Please reopen if the issue persists after reading my mail.

**Comment by cryptoPickle** [comment]
I know it is old issue, it might help someone.

I had same issue as well, what i found out that you can't access the encrypted realm file with multiple process. So if you are trying to access your file while your simulator opened the realm file. You should close the realm file from your simulator and try to access with realm studio.
