### ISSUE TITLE
Document how to downgrade Realm Studio

### ISSUE THREAD

**Issue by Janglinator** [realm/realm-studio#908]
**Describe the bug**
In the event that an update corrupts the application (as my previous bug has), I can find no way to download a previous version of Realm Studio.

**To Reproduce**
1.)  Update Realm

**Expected behavior**
Should be able to retrieve an older version from the website.

**Screenshots**

**Versions:**
 - OS: Mac 10.13.5

**Additional context**

**Comment by kraenhansen** [comment]
@Janglinator we have not be very vocal about this, but all versions of Studio is available for download via https://studio-releases.realm.io/

**Comment by Janglinator** [comment]
Thanks!  Maybe just a quick link add at the [Realm Studio](https://realm.io/products/realm-studio/) page would be adequate?  :)

**Comment by Janglinator** [comment]
Thanks!  I'll let you guys close this issue when you're ready.

**Comment by kraenhansen** [comment]
I believe that's now :)
