### ISSUE TITLE
Can't add multiple objects to a list in Realm Studio 2.6.1

### ISSUE THREAD

**Issue by bananaben** [realm/realm-studio#909]
**Describe the bug**
Hi Team, just updated to Realm Studio 2.6.1 on a Mac running OSX 10.13.6.

I am using studio to hardcode my objects (a), some objects contain a list where I pick multiple other objects (b). so A can have B1, B2, B3 etc.

I could do this fine in previous versions, however in the latest update whenever I click ‘add object’ to the list in the create new object form to add a second object, the button is non responsive and the page scroll indicator has disappeared.

This issue occurred for me on the latest version of Realm Studio for Windows as well.
Fix: Rolled back to Realm Studio 2.4.1, works fine on this version.

**To Reproduce**
1. Go to Realm Studio
2. Open Realm
3. Add new object with lists in it
4. Click add on the list, add object
5. Try click add again, will not work

**Expected behavior**
Ability to add multiple objects in the list of a 'master object' (works on 2.4.1)

**Versions:**
 - OS: OSX 10.13.6
 - Studio Version 2.6.1
 - Realm Object Server version 3.9.13

**Comment by kraenhansen** [comment]
This regression happed because a dependency added a `height` on a CSS class that didn't have a hight previously, which we didn't catch when testing the app after the upgrade. I'll have a release with a fix published in a couple of minutes.

Thanks for reporting this!

**Comment by kraenhansen** [comment]
@bananaben a fix for this issue just got released as Realm Studio 2.6.2, please allow your version of Studio to automatically update or download the latest version from https://realm.io/products/realm-studio.

**Comment by bananaben** [comment]
@kraenhansen thank you for such quick response and resolution. I can now add multiple objects to the list, however the scroll bar still disappears and therefore I can't actually edit the new object properly. Detailed in issue #916

**Comment by kraenhansen** [comment]
@bananaben okay thanks, I must have overlooked that part of the issue, I'll revisit it.
