### ISSUE TITLE
Better UI when tokens expire

### ISSUE THREAD

**Issue by astigsen** [realm/realm-studio#915]
Right now if you leave Studio running, the Realm Cloud JWT will at some point expire, and then when you try to use Studio to connect to a server or open a Realm from a server Studio will just tell you that that your user is invalid.

If this happens after you used to Cloud dashboard to login, the only way to refresh it is to go all the way back to the webpage and re-login there and then use that to re-open Studio, which is not at all intuitive.

We should have a better UI here and at least allow users to login again (or even better, make sure their tokens are refreshed in the background so they never expire).

Aha! Link: https://realmio.aha.io/features/ROS-105

**Comment by kraenhansen** [comment]
I updated the description above. I believe users experiencing this could restart Studio and then it would realize the expired token and ask the user to re-authenticate.

With regards to automatically refreshing the token, this is tracked by https://github.com/realm/raas/issues/322
