### ISSUE TITLE
No ability to scroll after adding object to list in realm studio

### ISSUE THREAD

**Issue by bananaben** [realm/realm-studio#916]
**Describe the bug**
Scroll bar disappears when adding object as list in realm studio.

**To Reproduce**
1. Go to realm studio
2. Click on your realm and add a new object (that includes a list of other objects)
3. select an object to add it to your list
4. Scroll bar disappears, can now longer scroll to click save / create

**Expected behavior**
The ability to continue scrolling in realm studio when you have added an object to a list

**Versions:**
 - OS: Mac 10.13.6
 - Studio Version 2.6.2

**Comment by kraenhansen** [comment]
I've concluded that is a bug in a library that we use to wrap the Bootstrap UI library in React components called Reactstrap. I've submitted an issue on their repo and a PR that fixes the issue https://github.com/reactstrap/reactstrap/pull/1190. I hope to get my changes merged and released soon-ish.

In the meantime I noticed that if you add a lot of items to the list and scroll down before starting to select an object for the first item, the UI is still somewhat usable.

Thanks again for reporting these issues!

**Comment by kraenhansen** [comment]
The PR got merged on the Reactstrap repository - I am still awaiting a release after their version 6.4.0.

**Comment by bananaben** [comment]
Hey team, is there an update to this issue? I keep having to go back to Studio v2.4.1 as this is the last versionI could find without this issue.

**Comment by kraenhansen** [comment]
Thanks for the nudge @bananaben. It looks like the 6.5.0 version of the dependent library got released with the fix we need to solve this. A simple upgrade on our side should do the trick.

**Comment by kraenhansen** [comment]
@bananaben - so sorry for the long wait on this one! This was fixed by #1009 (actually fixed already by #998).

The fix will be included in the next release of Realm Studio (3.0.7) - please allow Studio to automatically update and reopen this issue if it persists.
