### ISSUE TITLE
deleting an inserted row from nodejs write transaction

### ISSUE THREAD

**Issue by bajaga** [realm/realm-studio#920]
Sentry ID: e1c16dc886df47f4a5b71681b1f2b596

**Comment by kraenhansen** [comment]
I believe this is a duplicate of https://github.com/realm/realm-studio/issues/921 (or the other way around). There's a fix coming out within the next couple of minutes.

**Comment by kraenhansen** [comment]
This was fixed in the 2.8.0 version of Realm Studio - please allow the app to automatically upgrade and reopen this issue if it (unexpectedly) persists.
