### ISSUE TITLE
Can't upgrade from Studio 2.6.1 to 2.8.0

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#929]
**Describe the bug**
When clicking "yes" to below:
![image](https://user-images.githubusercontent.com/1215687/44999717-a82dfa80-afbf-11e8-9253-6ac27b422c9b.png)
Studio restarts, but has the same version, and ask me the same question.

**To Reproduce**
1. Install version 2.6.1
2. Click yes to upgrade

**Versions:**
 - OS: Mac
 - Studio Version: 2.6.1
 - Realm Object Server version: n/a

**Comment by kraenhansen** [comment]
I've experienced this myself recently. I suspect it might be the functionality that ensures Studio behaves like a singleton application that might behave differently in the 2.x version of Electron.

For the time being, it works if you close Studio entirely, wait for a few seconds and then open Studio again.

**Comment by kraenhansen** [comment]
When fixing this issue I should probably fix https://github.com/realm/realm-studio/issues/526 as well.

**Comment by kraenhansen** [comment]
It turns out this is in-fact an issue with the Electron auto-updater: https://github.com/electron-userland/electron-builder/issues/3269

**Comment by astigsen** [comment]
Is this the same issues as #936?

**Comment by kraenhansen** [comment]
No - I don't think so.

**Comment by kraenhansen** [comment]
It looks like the electron updater got fixed, but it hasn't been released yet. It's the next after version 3.1.2.

**Comment by nirinchev** [comment]
We downgraded electron-updater with https://github.com/realm/realm-studio/pull/953, which should have fixed it for versions 2.9.0 and newer.
