### ISSUE TITLE
Can't see data sizes of Realms in Studio

### ISSUE THREAD

**Issue by astigsen** [realm/realm-studio#938]
**Describe the bug**
After upgrading Studio to 2.8.0, I get the "Data Size" column, but it only shows "?":

<img width="308" alt="screen shot 2018-09-06 at 2 01 31 pm" src="https://user-images.githubusercontent.com/69422/45156156-99249380-b1dd-11e8-8e93-fd3a09d4d3ab.png">

The realms have all existed for months, so the sizes should be pre-calculated on the server, but maybe there is some relation to just having upgraded Studio (previous version I had did not show sizes)?

**Versions:**
 - OS: Mac
 - Studio Version 2.8.0
 - Realm Object Server version 3.9.11

**Comment by roberhofer** [comment]
@kraenhansen : Just note that users are running into the realm size reporting in Studio: https://realmio.slack.com/archives/C3VNX12BS/p1537392344000100 
https://forum.realm.io/t/total-size-of-realm-instance/1937

**Comment by cmelchior** [comment]
This might be a problem on the server. At least this is the network response I'm seeing when connecting to Cloud: `{"ros_sync_realm_state_size":[]}`

As a minimum, the array should report the size of the default Realm.
It is a bit unclear to me how to debug the server regarding this.

**Comment by bmunkholm** [comment]
@nirinchev Any clue on this?

**Comment by bmunkholm** [comment]
@kspangsege Do you have a clue?

**Comment by kspangsege** [comment]
My guess is that size computation is not enabled. That is, ROS does not enable it when launching this sync worker worker. If it is enabled in the sync worker, there should be a log message like this:

    Realm state size reporting: enabled

**Comment by roberhofer** [comment]
For context see as well: 
https://github.com/realm/realm-core-private/issues/259
And this larger, updated requirement here: https://realmio.aha.io/features/ROS-136

**Comment by kraenhansen** [comment]
See https://github.com/realm/realm-studio/issues/881#issuecomment-437316712 for a suggestion that would also fix this.

**Comment by roberhofer** [comment]
@kraenhansen : I would assume that this is addressed and implemented? 
If so please close this ticket.

**Comment by kraenhansen** [comment]
@roberhofer nope. Still finalizing this with https://github.com/realm/realm-studio/issues/1028.
