### ISSUE TITLE
Upgrade Studio to new JS version 2.17 - with care

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#949]
The new JS release 2.17.0 includes the new sync protocol that will help keep the server history smaller.
One important aspect to consider is that this update will then make Studio ONLY compatible with ROS 3.11.0 or later. This has to be warned about so automatic update is not happening.

Note that we did this previously with ROS 3.0, so we should use the same mechanism and principles.

**Comment by kraenhansen** [comment]
Just a friendly reminder: Following the semantic versioning scheme that we've used for this repository in the past the major version should be bumped if something like this is released. And a compatibility release channel could be created for a version which is backwards compatible but not actively maintained.

**Comment by nirinchev** [comment]
This is done now.
