### ISSUE TITLE
Releasing on cph-01 produces invalid binary for mac

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-studio#958]
**Describe the bug**
The build succeeds but the binary produced crashes with missing framework similar to 2.6.0.
Example: https://ci.realm.io/job/realm-studio/job/release/313/

**To Reproduce**
1. Change the node in jenkinsfile.release to force it to run on `macos-cph-01.cph.realm` and try to run the produced executable.

**Comment by kraenhansen** [comment]
I think a first step in solving this is detecting when a faulty package is produced - on Windows, MacOS or Linux, then we could start experimenting with running the builds on all macs and investigating failing builds resulting from that.
