### ISSUE TITLE
Cannot delete multiple rows in 2.9.0

### ISSUE THREAD

**Issue by ianpward** [realm/realm-studio#960]
Freshdesk Ticket ID: <a href='https://support.realm.io/helpdesk/tickets/1967' target='_blank'>1967</a> <br/> Freshdesk Ticket Agent: Eric.mossman<br/>Freshdesk Ticket Agent Email: eric.mossman@realm.io<br/>Ticket Priority: Low<br/>Freshdesk Ticket Description:<div>

**Comment by amalmo** [comment]
#959

**Comment by nirinchev** [comment]
Looks like #961 isn't a legitimate fix for that 😓 I'll have to look into it next week.

**Comment by nirinchev** [comment]
Not sure what I was looking at - it seems to be working now that I tested it.
