### ISSUE TITLE
Window size gets too small

### ISSUE THREAD

**Issue by eitanaviv** [realm/realm-studio#962]
**Describe the bug**
For no reason, the Realm Studio window size got resized into a small window and i cannot operate and do some operations.

**To Reproduce**
Can't reproduce.

**Expected behavior**
To have a normal sized window.

**Screenshots**
![image](https://user-images.githubusercontent.com/35567702/46595339-9371e480-cae0-11e8-8eef-f961c06e3b52.png)

**Versions:**
 - OS: Windows
 - Studio Version 2.9.0.336
 - Realm Object Server version - Don't use

**Additional context**
None.

**Comment by kraenhansen** [comment]
Can you manually resize the window back to it's original size? And what happens if you completely close down Studio and restart it?

**Comment by eitanaviv** [comment]
@kraenhansen, Funny thing, I can't open realm studio at all, only when opening .realm file directly (and still the realm studio itself does not open). Though, it seems that realm studio runs in background (tried to restart my PC, but still no change).
![image](https://user-images.githubusercontent.com/35567702/46613690-8541b980-cb1c-11e8-89a5-4594b5365ea3.png)

Back to my issue,
I can't resize the window of realm studio as it is size fixed, and when closing realm studio completely and reopen it gets even smaller,

**Comment by kraenhansen** [comment]
I suspect that a feature which restores window size and position (https://github.com/realm/realm-studio/pull/934) might be causing this somehow.

**Comment by eitanaviv** [comment]
@kraenhansen I'd be glad to provide any further information you need.

**Comment by kraenhansen** [comment]
@eitanaviv a fix for this got released with Studio v3.0.5 - please allow Studio to automatically upgrade or alternatively upgrade by downloading the latest version for windows: https://studio-releases.realm.io/latest/download/win-setup. Please reopen this issue if you're still experiencing it.
