### ISSUE TITLE
Don't offer to "upgrade" system realms to reference realms

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-studio#964]
**Describe the bug**
When looking at system Realms with "__" in front, you are offered to "upgrade" them to reference realms. This option should not be allowed. (similarly with Delete).

**Screenshots**
![image](https://user-images.githubusercontent.com/1215687/46739510-ff02b000-cca0-11e8-9d8a-456638a298ee.png)

**Versions:**
 - OS: Mac
 - Studio Version: 2.8.0

**Comment by nirinchev** [comment]
These Realms are usually hidden, so it's unlikely many people will shoot themselves in the foot.
