### ISSUE TITLE
Can't delete multiple objects only one each time

### ISSUE THREAD

**Issue by Evyasafmordechai** [realm/realm-studio#968]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Versions:**
 - OS: [e.g. Mac/Windows/]
 - Studio Version [e.g. 2.0.0]
 - Realm Object Server version [e.g. 3.0.1]

**Additional context**

**Comment by nirinchev** [comment]
Duplicate of https://github.com/realm/realm-studio/issues/960.
