### ISSUE TITLE
Realm Studio 3.0.0 for macOS Unable to open a realm at path (No schema selected).

### ISSUE THREAD

**Issue by softmastx** [realm/realm-studio#978]
**Describe the bug**
After updated to version 3.0.0 on macOS I can't open encrypted realm file !
It says "Unable to open a realm at path (No schema selected)"

**To Reproduce**
1. Close Realm Studio and reopen the realm file with the same error!

**Expected behavior**
Prompt to enter encryption key

**Screenshots**
https://ibb.co/fCjp2q

**Versions:**
 - OS: macOS 10.14
 - Realm Studio Version 3.0.0

**Comment by nirinchev** [comment]
Were you able to open it with Realm Studio 2.9.0? You can download a version of Studio that will not automatically upgrade to 3.0.0 [here](https://studio-releases.realm.io/v2.9.1-ros3.10.7).

**Comment by softmastx** [comment]
No issue with Realm Studio 2.9.0 at all. 
Realm Studio 3.0.0 doesn't support encrypted file?

**Comment by nirinchev** [comment]
It does - it was a bug due to upgrading one of our dependencies. I'll release a patch shortly.

**Comment by softmastx** [comment]
> It does - it was a bug due to upgrading one of our dependencies. I'll release a patch shortly.

Cheer!!
