### ISSUE TITLE
Failed creating the model "xxx": getClassFocus called before realm was loaded

### ISSUE THREAD

**Issue by softmastx** [realm/realm-studio#980]
**Describe the bug**
Cannot create a class inside Realm Studio for encrypted realm file!

**To Reproduce**
Tried to create difference class name with the same error!
No issue with un-encrypted realm file.

**Expected behavior**
New class is added.

**Screenshots**
https://ibb.co/cCSOCq
**Versions:**
 - OS: macOS 10.14
 - Studio Version 3.0.1, 2.9.0

**Comment by nirinchev** [comment]
Thanks for the report - it was indeed a bug on our part. I just pushed 3.0.2 with a fix for that.

**Comment by softmastx** [comment]
> Thanks for the report - it was indeed a bug on our part. I just pushed 3.0.2 with a fix for that.

@nirinchev Thanks for your prompt supporting and the incredible Realm Database!!!!
