### ISSUE TITLE
Blank screen after fresh install of 3.0.5

### ISSUE THREAD

**Issue by tomsjansons** [realm/realm-studio#995]
After doing a fresh install today of 3.0.5, when connecting to cloud instance, a blank screen opens.
![image](https://user-images.githubusercontent.com/1428917/48439123-3841aa80-e78e-11e8-9246-429311178b25.png)

If clicking on 'Connect to server', a smaller blank screen opens
![image](https://user-images.githubusercontent.com/1428917/48439045-10524700-e78e-11e8-856f-f443148e701e.png)

**Versions:**
 - OS: Windows 10
 - Studio Version: 3.0.5

**Comment by kraenhansen** [comment]
This was fixed by #998, #999 and #1000 - please allow the automatic update to update Studio to version 3.0.6 and reopen this issue if it persists.

**Comment by tomsjansons** [comment]
Fantastic, working now. Thank you!
